.codeclimate.yml, README.md, client/htmls/private/ajax/DesignBlueprint.html, client/htmls/private/ajax/DesignBlueprintAzure.html, client/htmls/private/ajax/Settings/CreateServiceCommand.html, client/htmls/private/js/settingscommon.js, server/README.md, server/lib/servicenow.js, server/model/blueprint/blueprint-types/instance-blueprint/vmware-blueprint/vmware-blueprint.js
The below issues was addressed
1. The List view for service command included unselected items.
2. During edit of the service command the checkboxes was getting selected.
=> Fix for service command settings issue

client/htmls/private/ajax/DesignBlueprint.html, client/htmls/private/ajax/DesignBlueprintAzure.html, client/htmls/private/ajax/DesignBlueprintVmware.html, server/lib/vmware.js, server/model/blueprint/blueprint-types/instance-blueprint/vmware-blueprint/vmware-blueprint.js
Templates Display for Docker on Azure, vmware and openstack blueprint creation
CAT-1591
Fixed vmware launch issue - CAT-1598
=> Templates Display for Docker on Azure, vmware and openstack blueprint creation

client/htmls/private/ajax/Settings/CreateProviders.html, server/model/classes/tasks/taskHistory.js, server/model/classes/tasks/taskTypeComposite.js, server/model/classes/tasks/tasks.js
1) Fixed Composite Task
2) Added checkbox for provider update
=> fixed composite task

.gitignore, server/app/model/classes/tasks/taskHistory.js
1) Added logs and config to gitignore
2) Fixed taskhhistory query to work with new version of mongo
=> App deploy fix

client/htmls/private/ajax/Controlpanel.html, client/htmls/private/css/catalyst.css, client/htmls/private/js/dev/dev.js, server/app/routes/routes_blueprints.js, server/app/routes/routes_openstack.js, server/app/routes/routes_organizations.js
=> Controlpanel fix

.gitignore, client/htmls/private/ajax/Settings/CreateProviders.html, server/app/cronjobs/jobs/provider-sync/sync-jobs/aws-sync.js, server/app/lib/awsCloudFormation.js, server/app/lib/ec2.js, server/app/lib/utils/dashboardUtil.js, server/app/lib/utils/providerUtil.js, server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/model/classes/masters/cloudprovider/awsCloudProvider.js, server/app/routes/routes_arm.js, server/app/routes/routes_cloudformation.js, server/app/routes/routes_instances.js, server/app/routes/routes_notification.js, server/app/routes/routes_provider.js, server/app/routes/routes_vmImages.js
Changes to allow creation of providers without providing access credentials. AWS API requests will be signed with access credentials of the IAM role attached to the catalyst instance.
Code refactoring needed in multiple modules to reduce callbacks and redefine abstractions.
=> [server] Enhancement to create providers without access credentials

client/htmls/public/Dashboard.html, client/htmls/public/css/Dashboard.css, client/htmls/public/js/dashboard.js
=> Added managed instances detail list in provider sync dashboard

client/htmls/private/ajax/Settings/CreateProviders.html
"Invalid AccessKey or SecretKey" popup is displayed on clicking edit button for AWS Provider
Tooltip display message changed
=> [client] Bug fix --> popup is displayed on clicking edit button for AWS Provider

client/htmls/private/ajax/Settings/CreateProviders.html, server/app/routes/routes_provider.js
Checkbox in add provider page replaced with radio buttons and let user select IAM, Access keys as option while adding new provider.
=> [client] Add provider UI improvements

server/app/model/unassigned-instances/package.json, server/app/model/unassigned-instances/unassignedInstances.js, server/app/model/unmanaged-instance/unmanaged-instance.js, server/app/routes/routes_providercommon.js, server/app/services/providerService.js, server/app/validators/instanceValidator.js
New unassigned instance apis and update to unmanged instances api
=> [server] Topic 1636 - instance api updates

client/htmls/private/ajax/Settings/providerSync.html
=> Added dummyJSON for unassigned catalyst status

client/htmls/private/ajax/Settings/providerSync.html, client/htmls/public/login.html
=> Added project and env in tables for instances also text changed 2015 to 2016 in login page

client/htmls/private/ajax/Settings/Dashboard.html, client/htmls/private/ajax/trackSettings.html, client/htmls/private/authSetup.js, client/htmls/private/index.html, client/htmls/private/js/dev/awsProduction.js, server/app/routes/routes.js
@revinjacob : kindly merge the code for jquery and server side changes.
=> Jquery and server side changes added.

client/htmls/private/js/dev/dev.js
=> [client] Hot fix: Containers tab shows containers of one instance

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewApp.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js
@revinjacob 
I have implemented the "new App deploy" in the application section.
=> Implemented the "new App deploy" in the application section

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerLaunchParams.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
@revinjacob : Have done some small UI fix for jenkins save. Have done the push before working on the pagination part.
=> Small Ui fixes

client/cat3/main.html, client/cat3/src/factory/workzoneFactories.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/globals/breadcrumb/breadcrumbService.js, client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintInfo.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/popups/addNewService.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpServices.html, client/cat3/src/partials/sections/dashboard/workzone/workzone.scss, client/cat3/src/partials/sections/dashboard/workzone/workzoneTreeMenu/workzoneTreeMenu.html, client/cat3/src/partials/theme.scss
1.removed id names in breadcrumb section in main.html and replaced id names with meaningful names.
2.Removed unnecessary divs in breadcrumb section in main.html.
3.Resolved docker image UI alignment issue in instance card view.
4.Changed some of the field names in blueprintInfo.html as per new API JSON response, removed some of the fields for azure provider as those fields are not required.
5.Defined new color in theme.scss & added the same color for autoKiller icon in Add New Service & CPServices Pages, fixed some of minor UI issues.
6.Removed globalErrorMessage section from main.html as we are not using it anywhere.
=> Blueprint Info related changes, ID name changes for breadcrumb, UI fixes in CP services Page.

client/cat3/src/factory/instanceServices.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpServicesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUpdateChefRunlist.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUpdateChefRunlistCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instancelog.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationUpdateChefRunlist.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationUpdateChefRunlistCtrl.js
1.Added Loader in instance Logs page to show loader on page delay
2. hiding the services tab in control panel page when an instance is associating with puppet server
3.resolved the issue with delay in opening the Chef Client Run popup in Instance & orchestration Pages, Added loader for delay in both the pages
4.indented newTaskCtrl.js & cpServicesCtrl.js files, removed extra lines & white spaces in between lines of code.
=> UI fixes & enhancements.

client/cat3/Gruntfile.js, client/cat3/main.html
New grunt build tasks added: build-qa and build-prod
=> Separated qa and prod build configs

client/htmls/private/ajax/Settings/providerSync.html
=> Added batch update tags in unassigned instances.

client/htmls/private/ajax/Dev.html, client/htmls/private/js/dev/dev.js
@gobindadas, Please review my code and merge it.
=> Fixed Docker issues

client/htmls/private/js/dev/dev.js
@gobindadas Please review my code and merge it.
=> Bug fixes For Docker checkbox allignment

client/cat3/main.html, client/cat3/src/factory/workzoneServices.js, client/cat3/src/main.js, client/cat3/src/partials/globals/ui-gridOptions/uiGridOptionsServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/application.scss, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCard.html, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCardsDirectives.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationCardDetails.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationCardDetailsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewApp.html
@revinjacob 
Added the App Deploy card view section and history list section in the application tab .
=> Added the App Deploy card  and history list in the application tab .

client/htmls/private/js/dev/awsProduction.js, server/app/lib/chef.js, server/app/model/blueprint/blueprint.js, server/app/routes/routes_instances.js
@Kaushik512 : Please check and merge.
=> Issue fixes for attribute edit during bootstrap and runlist order

client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerLaunchParams.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfo.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceSSH.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUpdateChefRunlist.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationUpdateChefRunlist.html, client/htmls/private/index.html, client/htmls/private/js/dev/awsProduction.js
@revinjacob : Out of the 7 bugs 5 have been resolved. Along with this me identified the api which was missing for the tasks not showing in control panel and 1 more issue which was on Divakar's name.
=> Resolved these bugs

client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARMCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormationCtrl.js
@revinjacob , Please review and merge the code for azurearms and cfts rendering data issue in pagination.
=> Fixed azurearms and cfts rendering data issue in pagination

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintInfo.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActions.html, client/cat3/src/partials/sections/dashboard/workzone/workzone.scss, client/cat3/src/partials/sections/dashboard/workzone/workzoneTreeMenu/workzoneTreeMenu.scss
1.Reduced card height, status image dimensions, reduced paddings in breadcrumb,tabs & card page to fit 10 cards & pagination controls without showing scrollbar.
2.Resolved Image & Keypair fields issue in blueprint Info
3.Internal UI bug fixes.
4.Getting Docker repo names list showing for docker blueprints, added CSS for the same.
=> UI Enhancements for card, Resolved internal issues.

server/app/model/app-deploy/app-data.js, server/app/routes/routes_appdeploy.js, server/app/services/appDeployService.js, server/app/services/taskService.js
=> Handle all error and some code fix for appdeploy

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/application/application.scss, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARM.html, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARMCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormation.html, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActions.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceActionGridTemplate.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss
1.integrated new API endpoint to get all the Blueprints
2.start/stop functionality in table view,changed start & stop icons in all the required places.
3.os icon issue in blueprint page.
4. Pagination control show/hide validations in AzureARM & Cloud Formation Pages.
=> integrated new API endpoint to get all the Blueprints,UI Fixes.

client/cat3/src/factory/workzoneServices.js, client/cat3/src/main.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintInfo.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerInstanceLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfo.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instancelog.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/viewNodes.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/viewNodesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzoneCtrl.js
@revinjacob , Please review the PR & merge.
=> Internal UI fixes,logout on tab refresh when token expired,, CAT-1803,1807,1795.

client/cat3/src/factory/authenticationAPI.js, client/cat3/src/factory/sessionFactory.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/viewNodes.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/viewNodesCtrl.js, client/cat3/src/utility/arrayUtility.js
handled user value is {} scenario in session storage.
@revin, Please review this PR & marge.
=> getpermissionset call is integrated with actual API.

client/cat3/src/factory/sessionFactory.js
=> Added null check for older session user

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApprove.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js
@revinjacob 
I have added the API for the application approve section.
=> Integrated  the API for the application approve section 

client/htmls/private/js/dev/application.js, server/app/lib/utils/masterUtil.js, server/app/model/app-deploy/app-data.js, server/app/model/app-deploy/app-deploy.js, server/app/model/app-deploy/deploy-permission.js, server/app/model/classes/tasks/tasks.js, server/app/routes/routes_appdata.js, server/app/routes/routes_appdeploy.js, server/app/services/appDeployService.js, server/app/services/taskService.js
=> Appdeploy api with async

client/cat3/main.html, client/cat3/src/factory/appPermissionServices.js, client/cat3/src/factory/sessionFactory.js, client/cat3/src/main.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/globals/header/header.scss, client/cat3/src/partials/globals/header/headerDashboard.html, client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/application/popups/configurePipelineViewCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARM.html, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARMCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormation.html, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormation.scss, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/popups/stackInfo.html, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/popups/stackInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
1.modified timestamp format in stack info popup, colors for status & validations changed in cloud formation & azureARM pages.
2.added loader at page level for newTask Page.
3.resolved projectId issue in configure pipeline view page.
4.Added a new file for appPermissions for showing the modules for different users.
5.removed [] for role in header, converted username to uppercase.
@revinjacob , Please review & merge.
=> Resolved CAT-1801, UI Fixes.

client/htmls/private/ajax/Settings/providerSync.html, client/htmls/public/Dashboard.html, client/htmls/public/css/Dashboard.css, client/htmls/public/js/dashboard.js
@kkn, Please review and merge.
=> Added tracked instances functionality for usages in track

server/app/model/classes/instance/instance.js, server/app/model/docker.js, server/app/services/appDeployService.js
=> Circular dependecy and some appdeploy bug fix

server/app/routes/routes_tasks.js
=> Code fix for jenkins task history

client/cat3/src/factory/workzonePermissionServices.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, client/htmls/private/index.html, server/app/model/classes/tasks/taskHistory.js
@revinjacob : QA bugs - CAT -1780, 1804,1805 has been resolved.(along with the permission set changes)
CAT  - 1802 i am reopening it again(its on my name) as the code needs to be changed for the condition that will satisfy the save. Shouldn't take much time to resolve and put the alert message.
Import By IP is failing . Please ask someone to test it again.
=> QA Bugs Resolved along with the changes for permission set

client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewApp.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js
@revinjacob 
I have added the docker deploy section in the app deploy .
=> Docker depoly section added

client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js
@revinjacob 
i have changed some thinks for app deploy (api integration )
=> Changes done for app deploy (api integration )

client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/application.scss, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromote.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromoteCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewApp.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js
@revinjacob 
I have changed some thinks  for app deploy and app promote and app approve section
=> Changes done for app deploy and app promote and app approve section

client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintInfo.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanel.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzone.html, client/cat3/src/partials/sections/dashboard/workzone/workzone.scss
1.Resolved CAT-1847.
2.Changed Control Panel Tabs from bs-tabs to nav-tabs.
3.Removed unnecessary console.log statements & white spaces.
4.Moved CSS styles from workzone.html to workzone.scss.
@revinjacob, Please review & merge this PR.
=> Resolved CAT-1847, Changed Control Panel Tabs from bs-tabs to nav-tabs.

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewApp.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js
@revinjacob 
I have changed the docker tag select box value with version .
=> Changes done for docker image tag

client/cat3/src/partials/sections/dashboard/workzone/workzoneCtrl.js
Different messages for admin and consumer/designer when no environments are available in workzone
=> CAT-1842, CAT-1843

client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanel.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActions.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpServicesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceImportByIp.html, client/cat3/src/partials/sections/dashboard/workzone/workzoneCtrl.js
1.Added function which will takes the user to containers page when clicked on docker icon from card & table views of the instance page.
2.Removed docker option from cpActions page & added the docker icon in control panel for instances which are associated with docker.
3.Resolved issue with service actions & indented controlPanelCtrl.js.
4.Added instance name in cpActionHistoryLogCtrl.js to show the instance name when user opens more info popup from cpActionServices Page.
=> Docker icon click navigation to containers tab & UI fixes.

client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunch.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/container/containerCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/container/popups/dockerplaypause.html, client/cat3/src/partials/sections/dashboard/workzone/container/popups/dockerreload.html, client/cat3/src/partials/sections/dashboard/workzone/container/popups/dockerstart.html, client/cat3/src/partials/sections/dashboard/workzone/container/popups/dockerstopplay.html, client/cat3/src/partials/sections/dashboard/workzone/container/popups/dockerterminate.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/popups/applicationUrl.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpLogs.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instancelog.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/chefLog.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/chefLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
@revinjacob : Please review and merge the PR which contains:
1- Fixed CAT-1857.
2- Handled comments for PR#235.
3- Fixed chef log polling via application.
=> Fixed CAT-1857 and chef log polling issue via application

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerLaunchParamsCtrl.js
@revinjacob, Please review the PR which have changes related to blueprint version dropdown & merge.
=> Added version dropdown in blueprint card, written logic to send theblueprint id based upon selected blueprint version for launch & blueprint moreinfo.

server/app/routes/routes_appdata.js, server/app/services/appDataService.js
=> created new response obj for appdata

client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzone.html, client/cat3/src/partials/sections/dashboard/workzone/workzone.scss
@revinjacob 
I have changed the application approve post object element name.
=> Changed the approve object element name

client/cat3/src/factory/instanceServices.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/popups/addNewService.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpServices.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistory.html
1.Resolved QA bugs CAT-1845,1902,1905,1903.
2.minor UI changes for instance card in mobile view.
3.RDP download for instance card view & cpActions Page(CAT-1904-instance table view is pending.)
@revinjacob, Please review the changes & merge.
=> Resolved CAT-1845,CAT-1902,CAT-1905,CAT-1903, RDP download for instance card view & cpActions Page.

client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfo.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationUpdateChefRunlistCtrl.js
@revinjacob : CAT - 1907(cookbook attribute), CAT - 1912($host in appUrl) , CAT - 1901(Regarding Job Links.
AppUrl creation and edit is now one single controller in control panel. It has been modified. Kindly review the changes once.
=> Resolved QA Bugs

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARM.html, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARMCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormation.html, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormation.scss, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/container/container.html, client/cat3/src/partials/sections/dashboard/workzone/container/container.scss, client/cat3/src/partials/sections/dashboard/workzone/container/containerCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
@revinjacob : Please review and merge. This PR contains:
1- CAT-1888
2- CAT-1898
3- CAT-1900
4- Fixed docker image issue and logo issue in instances table view.
=> Fixed CAT-1888, 1898, 1900

.codeclimate.yml, client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/application.scss, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCard.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeApp.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeAppCtrl.js
@revinjacob 
I have added "rowId" in deploy request object in new app deploy , updated the upgrade section .
=> Added rowId in deploy new app , updated the upgrade section

server/app/model/app-deploy/app-data.js, server/app/model/blueprint/blueprint.js, server/app/model/classes/tasks/taskTypeChef.js
=> Issue fix for promote app when app deployed via bootstrap

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/application/popups/configurePipelineViewCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintInfo.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfo.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceImportByIp.html
@revinjacob , Please review the changes and merge.
=> Resolved CAT-1886,1891,1924 & minor UI fixes.

client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionHistoryCtrl.js, client/htmls/private/css/catalyst.css, client/htmls/private/index.html
@revinjacob : Resolved CAT- 1929 and one dev bug.
Kindly review it once.
=> Resolved QA Bug and 1 Dev Bug

client/htmls/private/js/dev/awsProduction.js
@revinjacob and @kkn : Please review and merge the PR for CAT-1925
=> Fixed CAT-1925

client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/applicationHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/container/containerCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceNameEdit.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceNameEditCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js
@revinjacob : please review and merge the code for fixed table heights in all UI Grid tabs and added edit instance name validation.
=> Fixed table heights for all UI Grid tabs and added edit instance name validation

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/application.scss, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCard.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApprove.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromote.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromoteCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeApp.html
@revinjacob : CSS changes for app card and adding hrushikesh's changes. Kindly verify
=> Added Hrushikesh's changes

client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanel.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfo.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistory.html
=> 	Fixed some of the internal review comments, fixed some UI issues.

client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/workzone.scss, client/cat3/src/partials/sections/dashboard/workzone/workzoneCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzoneTreeMenu/workzoneTreeMenu.html, client/cat3/src/partials/sections/dashboard/workzone/workzoneTreeMenu/workzoneTreeMenu.scss
@revinjacob , Please review & merge changes.
=> Making the changes to show left tree always on page load, modified CSS as per the tree changes.

client/cat3/src/factory/workzoneServices.js, client/cat3/src/main.js, client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationCardDetails.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromote.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromoteCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerLaunchParams.html, client/cat3/src/partials/sections/dashboard/workzone/container/container.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/popups/addNewService.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionHistory.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpServices.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistory.html
@revinjacob : Please review and merge which contains : 
1- Fixed CAT-1939 and handled comments for PR#312
=> Fixed CAT-1939 and handled comments for PR#312

client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/application.scss, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCard.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzone.scss
@revinjacob 
I have changed the application sub tab button css , changed the position of action buttons . 
Changed the application card .
=> Changed the view text , action BTN , app card css

client/cat3/src/partials/globals/treeComponent/treeDirective.js, client/cat3/src/partials/globals/treeComponent/treeDirective.scss, client/cat3/src/partials/sections/dashboard/workzone/workzoneTreeMenu/workzoneTreeMenu.scss
Consistency with settings and track tree selections jQuery code
=> Workzone tree menu selection style made consistent 

client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARM.html, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormation.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistoryCtrl.js
=> Resolved CAT-1942, Added fixed height to new task wrapper to show internal scroll instead of showing outer scroll at page level.

client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARM.html, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormation.html, client/cat3/src/partials/sections/dashboard/workzone/container/container.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/workzone.scss
@revinjacob : please review and merge the PR for 
1- Fixed some css for action buttons in right side and views in left side of the panel.
2- Added update button for tasks and edit runlist name when runlist present for chef task.
=> Fixed some css for action buttons in right side and views in left side of the panel

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.html
@divakarkonakalla pls verify for all blueprint types
=> Modification to blueprint accordion to show open close buttons

client/htmls/public/Dashboard.html, client/htmls/public/js/dashboard.js
@kkn : please review and merge the code for 
1- Added managed,assigned and total instances for all provider in track
=> Added managed,assigned and total instances for all provider in track

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCard.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromoteCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeAppCtrl.js
@revinjacob 
I have changed the promote section for CAT-1939
pipeline view CAT-1941 and CAT-1841
I have changed serverRowId to rowId for CAT-1627.
=> Changes done for promote app , pipeline viewan

client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instancelog.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/chefLog.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/compositeLogs.html, client/cat3/src/partials/sections/login/login.html, client/cat3/src/partials/sections/login/login.scss
1. Media queries added for mobile & ipad device responsiveness for login page
2. Timestamp format change in orchestration ui grid,
3. Added fixed height for logs pages across application as per review comments.
=> Login Page Responsiveness, UI fixes.

client/cat3/src/factory/instanceServices.js, client/cat3/src/factory/workzonePermissionServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/applicationHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCardsDirectives.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationCardDetailsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARM.html, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARMCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormation.html, client/cat3/src/partials/sections/dashboard/workzone/container/container.html, client/cat3/src/partials/sections/dashboard/workzone/container/containerCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpLogs.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/startInstance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/stopInstance.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
=> Resolved 42 jshint errors, added a fix for internal scroll in cpLogs page.

client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromoteCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js
@revinjacob 
Added the version in summery view.
Changed the repo name and image name for docker deploy
=> Deploy and approve

client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js
@revinjacob 
Changed the version for revoke  .
=> Changed the version for revoke  

client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApprove.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeApp.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeAppCtrl.js
@revinjacob 
I have changed the approve and revoke method.
=> Combine two method in approve ctrl 

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationCardDetailsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeAppCtrl.js
@revinjacob 
I have removed the unused variable , changed the version section for summery view .
=> Removed the unuse var , create version var

client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCardsDirectives.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistoryCtrl.js
@revinjacob 
Changed the app name in application deploy for nexus.
Removed the jsint error and added the col withd for icons in ui grid
=> Removed the jsint error and added the col withd for icons in ui grid

client/cat3/src/partials/sections/dashboard/workzone/application/application.html, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js
@revinjacob 
Remove the extra space for refresh button and select card section i have changed .
=> Remove the extra space for refresh button and select card section i have changed 

client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeAppCtrl.js
@revinjacob 
I have changed the app name for nexus.
=> app name changed

client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromote.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActions.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
1.Prevented more than 1 click for new button in orchestration Page.
2.showing blueprints section on edit task defaultly if user selects a blueprint while creating.
=> Resolved CAT - 1961,1964 & 1975.

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js
@revinjacob 
I have completed ---
CAT-1968
CAT-1976
=> Changes done for approve comments and grid col width

client/cat3/src/partials/sections/card/card.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/popups/applicationUrl.html
=> Resolved CAT-1972.1977 & 1978.

client/cat3/src/clientRoutes.js, client/cat3/src/factory/authenticationFactory.js, client/cat3/src/factory/sessionFactory.js, client/cat3/src/main.js
Added token validation in main.js
made some changes in session and auth factory for token validation
added permission check in route config
=> Token Validation and auth check in route config

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunch.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceImportByIp.html
=> resolved import by ip issue & minor ui fixes.

client/cat3/src/factory/chefDataFormatterService.js, client/cat3/src/main.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationUpdateChefRunlistCtrl.js
Changed chef Data formatter functions to handle template format as well 
Removed the attribute call for role and template
=> CAT-1974: Icon not showing after moving back the template form runlist

client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceImportByIp.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html
@revinjacob, Please review & merge the changes.
=> Fixes for Import by ip & new task page.

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js
@revinjacob 
i have changed the isApprove comment section as per the modified API
=> Changed the isApprove comment section as per the modified API

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationCardDetails.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationCardDetailsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceActionGridTemplate.html
@revinjacob 
I have added the Execute method for  CAT-1992.
=> Changes done for CAT-1992

client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, client/htmls/private/css/catalyst.css, client/htmls/private/index.html, client/htmls/private/js/dev/awsProduction.js
@revinjacob : Resolved CAT - 1982 and one dev bug. Changes for blueprint card in design as per workzone.
=> Resolved CAT - 1982 and one dev bug

client/htmls/private/index.html
@Kaushik512 : Config Setup has been added in settings tree for chef, puppet and environment list. Kindly merge the code.
=> Config Setup added in Settings Tree

client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfo.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUpdateChefRunlist.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUpdateChefRunlistCtrl.js
=> Resolved CAT-1979,1993.

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerLaunchParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceActionGridTemplate.html
@revinjacob : CAT -1965 and api change for instances along with Import by IP fix. Kindly review it once.
=> Import By IP fix for pem file data, CAT -1965 and API change for instances for docker launch

client/cat3/main.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfo.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUpdateChefRunlist.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUpdateChefRunlistCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/chefLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/confirmJobRun.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/confirmJobRun.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/confirmJobRunCtrl.js
created separate confirm box for orchestration job run confirmation
wrote the code to check blueprint job and fetch the logs accordingly
=> CAT-1991: made changes in orchestration for blueprint job

client/htmls/private/ajax/Settings/CreateProviders.html
@kkn : Have added the tooltip for S3 Bucket Name. Kindly merge.
=> Tooltip added for S3 Bucket Name in providers

client/htmls/private/ajax/Settings/providerSync.html
@kkn @Kaushik512   : Have done UI modifications for S3 and RDS in ProviderSync. Kindly review and merge. The Jira Ticket ID - CAT 2021.
=> Changes in UI for ProviderSync - S3 and RDS

client/htmls/private/ajax/DesignBlueprint.html, client/htmls/private/ajax/DesignBlueprintAzure.html, client/htmls/private/ajax/DesignBlueprintVmware.html, client/htmls/private/ajax/Dev.html, client/htmls/private/ajax/Settings/CreateProviders.html, client/htmls/private/ajax/Settings/providerSync.html, client/htmls/private/ajax/assignTask.html, client/htmls/private/css/catalyst.css, client/htmls/private/index.html, client/htmls/private/js/dev/application.js, client/htmls/private/js/dev/applicationUpgradeAssignTask.js, client/htmls/private/js/dev/awsProduction.js, client/htmls/private/js/dev/dev.js, client/htmls/private/sshShell.html, client/htmls/public/Dashboard.html, client/htmls/public/js/dashboard.js
@revinjacob : Raising a PR for UI code catch up from dev branch.
=> Code Merge from dev branch - UI changes only

client/cat3/src/main.js, client/cat3/src/partials/globals/header/headerDashboard.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/chefLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/compositeLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/jenkinsLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzoneCtrl.js
@revinjacob Please review and merge
=> fir for CAT-2024,  CAT-2025

client/cat3/main.html, client/cat3/src/factory/authenticationFactory.js, client/cat3/src/factory/chefDataFormatterService.js, client/cat3/src/factory/workzonePermissionServices.js, client/cat3/src/factory/workzoneServices.js, client/cat3/src/main.js, client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/applicationHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCardsDirectives.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/chefLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/viewNodesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzoneCtrl.js, client/cat3/src/partials/sections/login/resetCtrl.js
@revinjacob , please review the changes & merge.
=> Resolved all the Jshint errors, fixed issue with the instance ids for chef & composite logs, removed some of unused code.

server/app/routes/v1.0/routes_organizations.js
@Kaushik512 Please update the jira ticket id
CAT-2035
=> api to list all containers without authentication

client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARMCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/azureARM/popups/removeARMDeploymentCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerInstanceLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerLaunchParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerRepoListCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/removeBlueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpServicesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/deleteInstanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceNameEditCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceRunPuppetClientCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceSSHCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUpdateChefRunlistCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/startStopInstanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/updateChefRunlistConfirmationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/viewRunListCtrl.js
=> Formatted & indented js files part-1.

client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/applicationHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCardsDirectives.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationApproveCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationCardDetailsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationCardLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationHistoryLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromoteCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/configurePipelineViewCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/deployNewAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/upgradeAppCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/popups/removeCFTCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/popups/stackInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/container/containerCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addJenkinsParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addJobLinksCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/assignNodesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/chefLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/compositeLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/confirmJobRunCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/jenkinsLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationLogCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationUpdateChefRunlistCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/runParamConfigCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/viewNodesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzoneCtrl.js
@revinjacob , Please merge the changes.
=> Formatted & indented js files part-2.

client/cat3/Gruntfile.js, client/cat3/app.js, client/cat3/src/clientRoutes.js, client/cat3/src/factory/access_permission_service.js, client/cat3/src/factory/authenticationAPI.js, client/cat3/src/factory/authenticationFactory.js, client/cat3/src/factory/authenticationServices.jst, client/cat3/src/factory/cacheServices.js, client/cat3/src/factory/chefDataFormatterService.js, client/cat3/src/factory/instanceServices.js, client/cat3/src/factory/localStorageFactory.js, client/cat3/src/factory/sessionFactory.js, client/cat3/src/factory/workzoneFactories.js, client/cat3/src/factory/workzonePermissionServices.js, client/cat3/src/factory/workzoneServices.js, client/cat3/src/main.js, client/cat3/src/partials/globals/chefSelectorComponent/chefSelectorComponent.js, client/cat3/src/partials/globals/chefSelectorComponent/chefSelectorService.js, client/cat3/src/partials/globals/header/headerDashboard.html, client/cat3/src/partials/globals/treeComponent/treeDirective.js, client/cat3/src/partials/globals/ui-gridOptions/uiGridOptionsServices.js, client/cat3/src/partials/sections/login/loginCtrl.js, client/cat3/src/partials/sections/login/resetCtrl.js, client/cat3/src/utility/arrayUtility.js, client/cat3/src/utility/paginationUtility.js, client/cat3/uiConfig.js
@revinjacob , Please merge the changes.
=> Formatted & indented js files part-3.

client/htmls/private/ajax/Aws-Production.html, client/htmls/private/ajax/Dev.html, client/htmls/private/css/catalyst.css, client/htmls/private/index.html, client/htmls/private/js/blueprintLaunch.js, client/htmls/private/js/dev/awsProduction.js
@kkn : I Have implemented the Blueprint launch from design. Kindly verify and merge.
=> Blueprint Launch from design implemented

client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerLaunchParamsCtrl.js, client/cat3/src/partials/theme.scss
@revinjacob : Added more width for Launch Params while docker blueprint launch and changed the blueprint border color with respect to design card.
=> Added width for Launch Parameters while docker launch

client/cat3/main.html, client/cat3/src/factory/workzonePermissionServices.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/workzone/application/pipelineCardsDirectives.js, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARMCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/container/containerCtrl.js, client/cat3/src/partials/sections/login/login.html, client/htmls/private/index.html
@revinjacob , Please review the changes and merge.
=> hot fix - Resolved CAT-2046,2047. 

server/app/lib/utils/masterUtil.js
=> Hot-fix - CAT 2054 - Containers are not showing for newly launched and imported nodes

client/cat3/src/factory/chefDataFormatterService.js, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARMCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormationCtrl.js
@kkn , @udeshrl : Raising a PR for CAT - 2083, CAT -2067 and CAT -2046
a) CFT and ARM  pagination resolved and fixed to 12 -  Fixed -  2046
b) CFT and ARM not refreshing after delete. Manually it has to be refreshed. - Fixed (UI Fix) - 2067
c) Deploy cookbooks are not retaining on editing chef task - Fixed  - 2083
=> Changes for CAT - 2083, CAT -2067 and CAT -2046

client/cat3/src/factory/chefDataFormatterService.js, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARMCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormationCtrl.js, server/app/lib/azure-arm.js, server/app/lib/utils/masterUtil.js, server/app/routes/v1.0/routes_arm.js
CAT-2054
CAT-2046 
CAT-2091
CAT-2083
CAT-2077
CAT-2067
=> Release v3.1.0 hot fixes

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromote.html, client/cat3/src/partials/sections/dashboard/workzone/application/popups/applicationPromoteCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/deleteInstanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/startStopInstanceCtrl.js
Please review and merge 
@kkn @Kaushik512
=> CAT-2034 error message handling

client/cat3/src/partials/sections/dashboard/workzone/application/applicationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/application/applicationHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARM.html, client/cat3/src/partials/sections/dashboard/workzone/azureARM/azureARMCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormation.html, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormationCtrl.js
@udeshrl : Kindly review and merge.
=> Fix for App Deploy pagination and increasing the CFT and ARM pagination number

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerLaunchParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/jenkinsLog.html, client/htmls/private/ajax/Settings/DashboardSettings.html, client/htmls/private/js/blueprintLaunch.js, client/htmls/private/js/dev/awsProduction.js
@udeshrl : Resolved CAT -2050, 2044 , 2068 and 2070. Kindly verify once.
=> Resolved QA bugs 

client/cat3/src/factory/instanceServices.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUpdateChefRunlistCtrl.js
=> CAT-2096: Cookbook attributes are not showing on edit

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
=> CAT-2051 Duplicate of chef tasks

client/cat3/src/partials/global.scss
Center alignment for header text in ui-grid implemented globally.
@udeshrl , Please review the changes & merge.
=> CAT-2084 Center alignment for header text

client/cat3/src/partials/sections/dashboard/workzone/application/popups/configurePipelineViewCtrl.js, server/app/cronjobs/cron-jobs.js, server/app/lib/utils/masterUtil.js, server/app/routes/v1.0/routes_appdeployPipeline.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/services/appDeployPipelineService.js, server/app/services/masterDataService.js, server/app/services/settingsService.js
@kkn  CAT-2112 Pipeline Configuration Issue Fixed
=> CAT-2112 Pipeline Configuration Issue Fixed

client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanel.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/popups/addNewService.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpServices.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceActionGridTemplate.html
=> CAT-2124 Control Panel redesign for instances

server/app/services/compositeBlueprintService.js
name added in response of create, list and get of composite blueprint API
=> CAT-2131 CRUD API implementation for composite blueprints

client/cat3/main.html, client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.scss, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/compositeBlueprintInfo.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/compositeBlueprintInfoCtrl.js
@udeshrl 
CAT-2108	 List existing composite blueprints in workzone.
CAT-2111	 Show Composite blueprint Info in popup.
CAT-2110	 launch composite blueprints in workzone.
CAT-2109	 Delete a composite blueprint from workzone.
=> Compsite blueprint in workzone

client/htmls/private/ajax/Aws-Production.html, client/htmls/private/ajax/compositeBlueprint.html, client/htmls/private/css/catalyst.css, client/htmls/private/index.html, client/htmls/private/js/blueprintCommon.js, client/htmls/private/js/blueprintLaunch.js, client/htmls/private/js/dev/awsProduction.js, client/htmls/private/js/selectorCompnetBlueprint.js
@udeshrl : Please review the code. Jira Tickets are as follows - CAT - 2100, CAT - 2105, 2114.
Items added -
a) Save of composite blueprints.
b) Listing of composite Blueprints in Design
c) Launch added for composite blueprints. Functionality yet to be implemented.
=> Code added for Composite Save and listing from design

server/app/model/blueprint-frame/blueprint-frame.js, server/app/model/blueprint-frame/package.json, server/app/routes/v1.0/routes.js, server/app/routes/v1.0/routes_blueprintFrames.js, server/app/validators/blueprintFrameValidator.js
blueprint frames API stub to launch composite blueprint
=> CAT-2132 Composite blueprint launch API implementation

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js
=> Changed the blueprint launch section as per API

client/cat3/main.html, client/cat3/src/main.js, client/cat3/src/partials/globals/toaster/angular-toastr.css, client/cat3/src/partials/globals/toaster/angular-toastr.tpls.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/compositeBlueprintInfo.html
@udeshrl 
i have added "toastr" for  message .
=> 	Added toastr 

client/htmls/private/ajax/Aws-Production.html, client/htmls/private/ajax/compositeBlueprint.html, client/htmls/private/css/catalyst.css, client/htmls/private/js/blueprintCommon.js, client/htmls/private/js/blueprintLaunch.js, client/htmls/private/js/dev/awsProduction.js, client/htmls/private/js/selectorCompnetBlueprint.js
=> More Info and Launch implemented from design for Composite Blueprints

client/htmls/private/index.html
@kkn : Please check and merge.
=> Jquery UI-version(css and js) upgraded

client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js
@udeshrl 
Changed the " timeout" time .For "toastr" message .
=> Changed the " timeout" time

client/htmls/public/css/auditTrailLogs.css, client/htmls/public/instanceLog.html, client/htmls/public/js/pagination.js
This PR contains following features:
Data population for instance log trail and showing data in table format.
Added popup to show logs for every instance action
implemented pagination, search functionality & sorting for instance log trail table.
Added new file pagination.js for implementing custom pagination in all Log trail pages.
@udeshrl , Please review the changes & merge.
=> CAT-2120 Instance Log Trail UI, Logs, Pagination, Search functionality & sorting. 

client/htmls/private/ajax/Settings/providerSync.html, server/app/model/blueprint/blueprint.js, server/app/model/classes/masters/vmImage.js
CAT-2158 - Unable to import Assigned Instance from provider sync page
CAT-2160 - Unable to delete AWS Provider
=> CAT-2158 and CAT-2160 fixes

client/htmls/public/css/auditTrailLogs.css, client/htmls/public/instanceLog.html, client/htmls/public/js/pagination.js, client/htmls/public/orchestrationLog.html
This PR contains following changes:
1.New file added for task list
2.New popup added for task action logs
3.API integration for logs polling in both instance & task pages.
4.Search & sorting implemented for task list table.
5.CSS changes for select, input box.
@udeshrl , Please review the changes and merge the PR.
=> CAT-2121 Orchestration(Task) Log Trail UI, Logs, Pagination, Search & Sorting.

client/cat3/src/partials/globals/toaster/angular-toastr.tpls.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/removeBlueprintCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/popups/removeCFTCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfoCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpServicesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/deleteInstanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUpdateChefRunlistCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/startStopInstanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addJenkinsParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addJobLinksCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/confirmJobRunCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
@udeshrl 
Added toastr and changed the alert validation only workzone
=> Added toastr and changed the alert validation 

client/htmls/private/ajax/compositeBlueprint.html, client/htmls/private/css/catalyst.css, client/htmls/private/js/blueprintCommon.js
@udeshrl 
Changes done for composite blueprint edit version .
=> changes done for composite blueprint edit

server/app/services/taskService.js
=> Attached instanceName for all checf tasks and jenkinsLog for all jenkins tasks-2115

client/htmls/private/ajax/Aws-Production.html, client/htmls/private/index.html, client/htmls/private/js/blueprintCommon.js, client/htmls/private/js/dev/awsProduction.js
@udeshrl : Please review and merge. Composite update and delete has been implemented.
CAT - 2104 and CAT -  2155(copy not yet implemented)
=> Changes for composite update and delete completed in design

client/htmls/private/ajax/Settings/scriptList.html, client/htmls/private/js/scriptList.js, server/app/cronjobs/cron-jobs.js, server/app/model/classes/instance/instance.js, server/app/model/classes/tasks/taskTypeScript.js, server/app/model/classes/tasks/tasks.js, server/app/model/file-upload/file-upload.js, server/app/model/scripts/scripts.js, server/app/routes/v1.0/routes.js, server/app/routes/v1.0/routes_fileUpload.js, server/app/routes/v1.0/routes_scripts.js, server/app/routes/v1.0/routes_tasks.js, server/app/services/scriptService.js, server/install.js
CAT-2163/CAT-2126 Server Side changes for script executor(Orchestration) for Powershell and Bash
=> CAT-2163/CAT-2126 

client/htmls/public/instanceLog.html
corrected the field name for if to resolve size issue.
@udeshrl , Please merge the PR.
=> CAT-2120,2121 Instance & Orchestration(Task) Log Trail UI, Logs, Pagination, Search & Sorting.

client/htmls/private/ajax/Settings/scriptList.html, client/htmls/private/css/catalyst.css, client/htmls/private/js/scriptList.js, server/app/routes/v1.0/routes_fileUpload.js
@udeshrl : Please review and merge.
=> Script Viewer added in Settings

client/htmls/private/ajax/Settings/chefSync.html, client/htmls/private/js/scriptList.js, server/app/model/d4dmasters/environments.js, server/app/routes/v1.0/routes_chef.js, server/app/routes/v1.0/routes_fileUpload.js, server/app/services/settingsService.js
CAT-2142/CAT-2163(Import Node by chef and Environment List Issue)
Delete a uploaded file if any error will come in script creation.
Resolved merge conflicts
=> CAT-2163/CAT-2126(Server Side change for Script Executor for Orchestation)

client/htmls/private/ajax/Settings/chefSync.html, server/app/cronjobs/chef-sync/chef-sync.js, server/app/cronjobs/cron-jobs.js, server/app/lib/chef.js, server/app/routes/v1.0/routes_chef.js
Data tables and cron job issue
=> Topic 2153 release

client/htmls/private/ajax/Settings/chefSync.html, server/app/cronjobs/chef-sync/chef-sync.js, server/app/cronjobs/chef-sync/package.json, server/app/cronjobs/cron-jobs.js, server/app/model/dao/chefDao.js, server/app/routes/v1.0/routes_chef.js
CAT-2199 fixed
Durgesh1988 	Add functionality for wrong chef server credentials
=> CAT-2199 fixed

client/htmls/public/instanceLog.html
=> Resolved CAT-2192 - OS icon is not showing correctly for the nodes imported from Provider

server/app/cronjobs/chef-sync/chef-sync.js, server/app/lib/utils/sshexec.js, server/app/model/classes/instance/instance.js, server/app/model/dao/chefDao.js, server/app/model/unassigned-instances/unassigned-instances.js, server/app/model/unmanaged-instance/unmanaged-instance.js, server/app/routes/v1.0/routes_chef.js, server/app/routes/v1.0/routes_organizations.js, server/app/routes/v1.0/routes_providercommon.js
CAT-2206  Unable to import nodes from chef server
CAT-2204  User shouldn’t be able to import nodes with incorrect credentials 
CAT-2161  During deletion of terminated instances from catalyst through cron job, delete it from chef server also.
=> CAT-2204, CAT-2206 and CAT-2161 Fixed

client/cat3/src/clientRoutes.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js, client/cat3/src/partials/sections/dashboard/design/design.html, client/cat3/src/partials/sections/dashboard/design/design.scss, client/cat3/src/partials/sections/dashboard/design/designCtrl.js, client/cat3/src/partials/sections/dashboard/design/designServices.js, client/cat3/src/partials/sections/dashboard/design/services/blueprintListServices.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html, client/cat3/src/partials/sections/dashboard/design/view/designListView.html, client/cat3/src/partials/sections/dashboard/design/view/designSubMenu.html, client/cat3/src/partials/sections/dashboard/design/view/filterSidebar.html, client/cat3/src/partials/sections/dashboard/design/view/popups/blueprintCopy.html
@udeshrl 
Integrated API and changed some positions of structure .
=> Integrated API and changed some positions of structure

client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.html
@udeshrl 
Composite Template type name changed CAT-2156
=> Composite Template type name changed CAT-2156

client/htmls/public/instanceLog.html
=> CAT-2213 - AWS icon is showing in Providers column in audit trial page for the nodes imported by IP.

CHANGELOG.md, client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanel.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpInfo.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/deleteInstance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/deleteInstanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceActionGridTemplate.html, client/cat3/src/partials/sections/dashboard/workzone/workzone.scss, client/htmls/public/Dashboard.html, client/htmls/public/css/Dashboard.css, client/htmls/public/js/dashboard.js
=> workzone and track enhancements

client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpServicesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
@udeshrl , Please review and merge the changes.
=> Resolved CAT-2176 & 2183.

client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/dockerInstanceLogsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/assignNodes.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/assignNodesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
=> Resolved CAT-2140 - For Script Executor "NA" should not be shown in Job links column instead show View nodes and Script Name.

client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js, client/cat3/src/partials/sections/dashboard/design/designCtrl.js, client/cat3/src/partials/sections/dashboard/design/services/blueprintListServices.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html, client/cat3/src/partials/sections/dashboard/design/view/designListView.html
=> Design srikanth

client/htmls/private/js/blueprintCommon.js, client/htmls/private/js/dev/awsProduction.js
=> Composite Filter for Org,Proj and BU, Multiple Delete Of Composite Blueprints

client/htmls/public/css/auditTrailLogs.css
=> Page Name UI changes.

client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/design.scss, client/cat3/src/partials/sections/dashboard/design/services/blueprintCreateServices.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html, client/cat3/src/partials/sections/dashboard/design/view/designSubMenu.html
=> Azure Software Stack and OS Image creation  and listing implemented

client/htmls/public/instanceLog.html
=> CAT-2222 - Incorrect status is showing in control panel and Audit trial page when Instance is bootstrapping.

client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/services/blueprintCreateServices.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html
=> VmWare BP - OS and Software Stack along with some code refactor

server/app/cronjobs/provider-rds-s3-sync/AWSRDSS3ProviderSync.js, server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/model/classes/tasks/taskTypeScript.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/routes/v1.0/routes_organizations.js, server/app/services/resourceService.js
Environment is not selecting by default in Edit projects page when new environment is created.
=> CAT-2248 Fixed

client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js
=> Resolved 2223 - Change the popup title when user clicks Launch button for composite blueprint 

client/htmls/private/ajax/Settings/CreateImages.html, client/htmls/private/ajax/Settings/CreateProviders.html, client/htmls/private/ajax/Settings/ImagesList.html, client/htmls/private/ajax/Settings/ProvidersList.html, server/app/cronjobs/docker-container-sync/DockerContainerSync.js, server/app/cronjobs/provider-rds-s3-sync/AWSRDSS3ProviderSync.js, server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/lib/utils/masterUtil.js, server/app/model/classes/masters/cloudprovider/awsCloudProvider.js, server/app/model/classes/masters/cloudprovider/azureCloudProvider.js, server/app/model/classes/masters/cloudprovider/hppublicCloudProvider.js, server/app/model/classes/masters/cloudprovider/openstackCloudProvider.js, server/app/model/classes/masters/cloudprovider/vmwareCloudProvider.js, server/app/model/classes/masters/vmImage.js, server/app/model/unassigned-instances/unassigned-instances.js, server/app/routes/v1.0/routes_cloudformation.js, server/app/routes/v1.0/routes_instances.js, server/app/routes/v1.0/routes_provider.js, server/app/services/resourceService.js
CAT-2255 Migration Issues - Terminated Instance Containers are showing in Containers tab(Fixed)
CAT-2251 For creating a Provider, orgId should be as rowId not mongodb Id.
=> CAT-2251 and CAT 2255 Fixed

client/htmls/private/ajax/Settings/CreateImages.html, client/htmls/private/ajax/Settings/ImagesList.html, client/htmls/private/ajax/Settings/ProvidersList.html, server/app/cronjobs/docker-container-sync/DockerContainerSync.js, server/app/model/classes/masters/cloudprovider/awsCloudProvider.js, server/app/model/classes/masters/cloudprovider/azureCloudProvider.js, server/app/model/classes/masters/cloudprovider/hppublicCloudProvider.js, server/app/model/classes/masters/cloudprovider/openstackCloudProvider.js, server/app/model/classes/masters/cloudprovider/vmwareCloudProvider.js, server/app/model/classes/masters/vmImage.js, server/app/routes/v1.0/routes_cloudformation.js, server/app/routes/v1.0/routes_instances.js
CAT-2255 Migration Issues - Terminated Instance Containers are showing in Containers tab(Fixed)
CAT-2251 For creating a Provider, orgId should be as rowId not mongodb Id.
=> Team-wise Access Control

server/app/cronjobs/aws-cost-aggregation/AWSCostAggregation.js, server/app/cronjobs/aws-usage-aggregation/AWSUsageAggregation.js, server/app/cronjobs/provider-rds-s3-sync/AWSRDSS3ProviderSync.js, server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/cronjobs/provider-tags-aggregation/ProviderTagsAggregation.js, server/app/model/classes/instance/instance.js, server/app/routes/v1.0/routes_track.js, server/install.js
CAT-2257 Fixed and Track Changes Required(CAT-2256)
=> CAT-2257 and CAT-2256 Fixed

server/app/model/classes/masters/cloudprovider/keyPair.js, server/app/routes/v1.0/routes_chef.js, server/app/routes/v1.0/routes_provider.js, server/app/routes/v1.0/routes_providercommon.js
CAT-2258 Fixed.(When instance is imported from chef server its not showing in Audit trail page)
=> CAT-2258 Fixed.

client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/htmls/private/ajax/Settings/ProvidersList.html, client/htmls/public/js/dashboard.js
Report and track usage trend changes
=> Topic workzone enhancements

client/htmls/private/ajax/Settings/ProvidersList.html, server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/routes/v1.0/routes_organizations.js
Team-level Access change for more then one team with different envs and projects
=> Team-level Access change for more then one team with different envs and Projects

client/htmls/private/ajax/Settings/ProvidersList.html
=> Check for Error in Provider Report

server/app/services/reportsService.js
=> Error messages updated for queries not supported

client/htmls/private/ajax/Settings/ProvidersList.html
=> Added dropdown for year and month, reset of select dropdowns

client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/htmls/private/ajax/Settings/CreateZabbixServer.html, client/htmls/private/ajax/Settings/ZabbixServerList.html, client/htmls/private/index.html, server/app/lib/utils/masterUtil.js, server/app/lib/zabbix.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/model/blueprint/blueprint.js, server/app/model/classes/instance/instance.js, server/app/model/classes/tasks/taskTypeChef.js, server/app/model/d4dmasters/configmgmt.js, server/app/model/d4dmasters/d4dmastersmodelnew.js, server/app/routes/v1.0/routes.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/routes/v1.0/routes_instances.js, server/app/routes/v1.0/routes_organizations.js, server/app/routes/v1.0/routes_zabbix.js, server/package.json
Implemented api and model for app details - CAT-2275
=> Topic 2225 release

client/cat3/src/partials/globals/header/headerDashboard.html
=> Changed Help link in headers to Read the Docs

server/app/model/resource-costs/resource-costs.js, server/app/services/reportsService.js
CAT-2292 Instances are not listing based on the Filter selection by provider in Workzone
CAT-2293 In Cost Trend Report, Total monthly running cost is showing as null
=> Fix for CAT-2293 and CAT-2292

client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, server/app/model/classes/tasks/tasks.js
=> Added radio buttons to select isSudo true/false for script task.

server/app/lib/utils/apiUtil.js, server/app/model/unassigned-instances/unassigned-instances.js, server/app/routes/v1.0/routes_trackedInstances.js, server/app/services/instanceService.js
@kkn : Please check and merge.
=> CAT 2303 - Server side changes for tracked instances.

client/cat3/src/partials/sections/card/card.scss, client/htmls/private/ajax/DesignBlueprint.html, client/htmls/private/ajax/DesignBlueprintAzure.html, client/htmls/private/ajax/DesignBlueprintVmware.html, client/htmls/private/js/blueprintLaunch.js, client/htmls/private/js/dev/awsProduction.js, server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/lib/utils/apiUtil.js, server/app/model/log-trail/instanceLog.js, server/app/model/unassigned-instances/unassigned-instances.js, server/app/routes/v1.0/routes_cloudformation.js, server/app/routes/v1.0/routes_instances.js, server/app/routes/v1.0/routes_trackedInstances.js, server/app/services/instanceService.js
CAT-2278,2303 and 1601 Fixed
Resolved merge conflicts
=> Dev-CAT-2278,2303 and 1601 Fixed

client/htmls/private/js/blueprintLaunch.js, client/htmls/public/awsCapacity.html, client/htmls/public/css/capacity.css, client/htmls/public/js/awsCapacity.js, server/app/routes/v1.0/routes_provider.js, server/app/routes/v1.0/routes_trackedInstances.js
@hrushikesh07 : Please verify and merge.
=> Implemented Capacity Dashboard in Track

README.md, client/htmls/private/ajax/Settings/providerSync.html, client/htmls/public/js/dashboard.js, server/app/cronjobs/aws-cost-aggregation/AWSCostAggregation.js, server/app/services/resourceService.js
Provider Sync changes for private IP Address(Unassigned and assigned Instance)			
Add unassigned Instances for Cost Aggregation
=> Provider Sync Fixes

client/htmls/private/ajax/Settings/providerSync.html, client/htmls/public/js/awsCapacity.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/routes/v1.0/routes_provider.js
Implementing Tag Update functionality check for corresponding updated tag-values and blank tag-value check.
=> CAT-2327 Implementation

client/htmls/private/ajax/Settings/CreateOrg.html, client/htmls/private/ajax/Settings/providerSync.html, client/htmls/private/js/settingscommon.js, client/htmls/public/instanceLog.html, client/htmls/public/js/awsCapacity.js, server/app/model/classes/instance/instance.js, server/app/model/unassigned-instances/unassigned-instances.js, server/app/model/unmanaged-instance/unmanaged-instance.js, server/app/routes/v1.0/routes_cloudformation.js, server/app/routes/v1.0/routes_provider.js, server/app/services/instanceService.js
CAT-2333(IP address is not changing on restarting the instances)
CAT-2335(Unable to create provider when billing cost is not entered)
CAT-2334 (user is able to update same tags for BU, Project and Environment)
CAT-2332 (Data table issue in Provider Sync)
=> CAT-2333/CAT-2335/CAT-2334 Fixed

client/htmls/public/Dashboard.html
=> Added tooltip for cost and usage in aws reports

client/htmls/public/js/dashboard.js
=> Y label added for CPU utilization

client/cat3/src/main.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.js, client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/analyticsTreeMenu.html, client/cat3/src/partials/sections/dashboard/analytics/view/cost.html, client/cat3/src/partials/sections/dashboard/dashboardCtrl.js, client/cat3/src/partials/sections/dashboard/genericServices.js
@udeshrl 
I have create a common service for left menu  hide show , used a box model for chart .
=> Chart panel changes done

client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.scss
=> UI layout changes in Dashboard Page to hide/show left menu panel, added CSS for all HTML elements for styling.

client/cat3/main.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.js, client/cat3/src/partials/sections/dashboard/analytics/analytics.scss, client/cat3/src/partials/sections/dashboard/analytics/controller/capacityCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/analyticsTreeMenu.html, client/cat3/src/partials/sections/dashboard/analytics/view/capacity.html
=> Added New HTML & JS files for capacity section, changed UI elements to show data in capacity & usage views also.

client/cat3/src/partials/sections/dashboard/analytics/controller/capacityCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/usageCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/analyticsTreeMenu.scss, client/cat3/src/partials/sections/dashboard/analytics/view/capacity.html, client/cat3/src/partials/sections/dashboard/analytics/view/usage.html
@udeshrl , please merge the changes.
=> Changed options & object names for UI grid for capacity & usage, added CSS to show selected item in the left tree menu.

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.js, client/cat3/src/partials/sections/dashboard/analytics/analytics.scss, client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/data/cost.json, client/cat3/src/partials/sections/dashboard/analytics/data/costTrend.json, client/cat3/src/partials/sections/dashboard/analytics/view/cost.html
@udeshrl 
I have changed the chart view and added "costTrend" chart .
=> Changed the chart view

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.js, client/cat3/src/partials/sections/dashboard/analytics/analytics.scss, client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/data/cost.json, client/cat3/src/partials/sections/dashboard/analytics/view/cost.html
@udeshrl 
I have changed filter for usage and cost .
=> Changes done for filter

client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.js
=> API integrated to get available providers for an org, to get regions/zones for a selected provider is done.

client/cat3/main.html, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.js, client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/data/cost.json, client/cat3/src/partials/sections/dashboard/analytics/view/analyticsTreeMenu.html, client/cat3/src/partials/sections/dashboard/analytics/view/cost.html
@udeshrl 
I have changed the chart color codes .Added body loader for service call .
=> Analytics changes

client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js
@udeshrl 
Added trends API for cost
=> Added trends API for cost

client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.js, client/cat3/src/partials/sections/dashboard/analytics/analytics.scss
=> Added org, BU, Project, Provider text on top of names for better understanding, clean up CSS, removed important from all CSS attributes.

client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParams.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js, client/htmls/private/ajax/Aws-Production.html, client/htmls/private/ajax/DesignBlueprint.html, client/htmls/private/ajax/DesignBlueprintAzure.html, client/htmls/private/ajax/DesignBlueprintVmware.html, client/htmls/private/ajax/devHTML/blueprint.html, client/htmls/private/index.html, client/htmls/private/js/blueprintLaunch.js, client/htmls/private/js/dev/awsProduction.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/routes/v1.0/routes_blueprints.js
CAT-2352 - Unable to launch blueprints from Design 
CAT-2353 - Enter a Domain Name popup should not be shown for the blueprints when "NO" options is set during blueprint creation 
CAT-2351 - Disable OK button when it throws error during blueprint launch
=> CAT-2351/CAT-2352/CAT-2353 fixed

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.js, client/cat3/src/partials/sections/dashboard/analytics/analytics.scss
this PR contains the following changes:
1.Integrated API's to get list of managed, assigned & unassigned instance list, 
2.implemented search of instances through key words, 
3.implemented multi select component to select more than 1 resources at a time.
=> Right Filter changes for Usage.

client/htmls/public/containerLog.html, client/htmls/public/css/auditTrailLogs.css
This PR contains the following things:
1.Added new HTML for Container Logs audit trail.
2.modified CSS for container Logs loader.
3.API integration done for container action table data
4.API integration done for container action logs per action.
=> CAT -2354 - Audit Trail for Docker Containers.

client/htmls/private/ajax/Settings/bgWizard.html, client/htmls/private/ajax/Settings/projWizard.html, client/htmls/private/ajax/Settings/providerWizard.html, client/htmls/private/ajax/Settings/settingsWizard.html, server/install.js
CAT-2368/CAT-2370/CAT-2374/CAT-2376 Fixed
=> CAT-2368/CAT-2370/CAT-2374/CAT-2376 Fixed

client/htmls/private/ajax/Settings/Dashboard.html, client/htmls/private/ajax/Settings/bgWizard.html, client/htmls/private/ajax/Settings/configManagementWizard.html, client/htmls/private/ajax/Settings/devopsRolesWizard.html, client/htmls/private/ajax/Settings/dockerWizard.html, client/htmls/private/ajax/Settings/envWizard.html, client/htmls/private/ajax/Settings/galleryWizard.html, client/htmls/private/ajax/Settings/jenkinsWizard.html, client/htmls/private/ajax/Settings/projWizard.html, client/htmls/private/ajax/Settings/providerWizard.html, client/htmls/private/ajax/Settings/scriptWizard.html, client/htmls/private/ajax/Settings/serviceCommandWizard.html, client/htmls/private/ajax/Settings/settingsWizard.html, client/htmls/private/ajax/Settings/teamWizard.html, client/htmls/private/ajax/Settings/vmImageWizard.html, client/htmls/private/css/wizardBg.css, client/htmls/private/js/settingscommon.js
@udeshrl : Please merge.
Resolved CAT - 2379 - Done
2376 - Done
2374 - seed data issue(done)
2371 - Done
2376 - Done
2368 - done
2369 - done
2370 - done
2379 - Done.
2371 - done.
2372 - done.
=> Bugs Resolved for Settings Wizard

client/htmls/private/ajax/DesignBlueprint.html, client/htmls/private/ajax/DesignBlueprintAzure.html, client/htmls/private/ajax/DesignBlueprintVmware.html, client/htmls/private/js/blueprintCommon.js, server/app/routes/v1.0/routes_organizations.js
CAT-1563 - Org/BU/Project Dropdown values are not populating in Exiting Blueprints tab When two organizations are associated to Superadmin.
=> CAT-1563 Fixed

server/app/routes/v1.0/routes_organizations.js
=> CAT-2399 Fixed

server/app/routes/v1.0/routes_d4dMasters.js, server/app/routes/v1.0/routes_organizations.js
=> CAT-2400 Fixed

server/app/cronjobs/docker-container-sync/DockerContainerSync.js, server/app/routes/v1.0/routes_instances.js
Implemented the Docker container status.
Ready for code review
@kkn
=> Implemented the Docker container status

client/htmls/public/containerLog.html
=> UI changes for docker container audit trail.

client/htmls/public/containerLog.html, client/htmls/public/instanceLog.html
=> minor UI changes releted to table header text, refresh table related changes.

client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/usageCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/cost.html, client/cat3/src/partials/sections/dashboard/analytics/view/usage.html
@udeshrl 
I have added animation for chart .
=> Added animation for chart

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.scss, client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/usageCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/cost.html, client/cat3/src/partials/sections/dashboard/analytics/view/usage.html
=> Topic cloud analytics

client/htmls/private/js/blueprintCommon.js
=> Resolved CAT-2415 for composite blueprint

client/htmls/public/containerLog.html, server/app/cronjobs/docker-container-sync/DockerContainerSync.js, server/app/model/classes/instance/instance.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/routes/v1.0/routes_instances.js
Containers are still showing when instances are terminated
=> CAT-2409 Fixed

client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.js, client/cat3/src/partials/sections/dashboard/analytics/controller/usageCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/usage.html
@udeshrl 
I have added usage report.
=> Usage report added

client/cat3/main.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html, client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUsage.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceUsageCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzoneCtrl.js
1.Added usage icon for instances which are not imported by ip.
2.Added new popup to show usages for selected instance.
=> Usage for instances in workzone.

server/app/routes/v1.0/routes_blueprints.js
Implemented the Service Delivery Check.
Ready for code review.
@kkn 
@Kaushik512
=> Implemented the Service Delivery Check

client/cat3/Gruntfile.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/design.html, client/cat3/src/partials/sections/dashboard/design/design.scss, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html
@hrushikesh07 : Please merge. Grunt file updated.
=> Design Changes

server/app/model/blueprint/blueprint-types/arm-template-blueprint/arm-template-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/azure-blueprint/azure-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/openstack-blueprint/openstack-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/vmware-blueprint/vmware-blueprint.js, server/app/model/classes/instance/instance.js, server/app/routes/v1.0/routes_chef.js, server/app/routes/v1.0/routes_organizations.js, server/app/routes/v1.0/routes_providercommon.js
Implementation of tag servers whenever a new server is coming into catalyst.
Basically 4 scenarios : 
1. Launching blueprint
2. Importing by IP
3. Importing from Chef server
4. Import from provider
@kkn 
@Kaushik512
=> Implementation of tag servers

client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html
=> Changed rowid for project and region listing in cft

client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceImportByIp.html, client/htmls/private/ajax/Aws-Production.html, client/htmls/private/ajax/Settings/chefSync.html, client/htmls/private/js/dev/awsProduction.js
=> Added Service Delivery check while creating new blueprint.

client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js, client/cat3/src/partials/sections/dashboard/design/design.html, client/cat3/src/partials/sections/dashboard/design/design.scss, client/cat3/src/partials/sections/dashboard/design/designCtrl.js, client/cat3/src/partials/sections/dashboard/design/designServices.js, client/cat3/src/partials/sections/dashboard/design/services/blueprintListServices.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html
@udeshrl 
I have changed the design HTML.
=> Design HTML changed

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/globals/header/header.scss, client/cat3/src/partials/globals/header/headerDashboard.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParams.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceImportByIp.html, client/htmls/private/ajax/Settings/chefSync.html
=> Added tag server check, added dropdown to select a server to tag.

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, client/htmls/private/js/dev/awsProduction.js, server/app/model/blueprint/blueprint.js, server/app/model/classes/tasks/tasks.js, server/app/routes/v1.0/routes.js, server/app/routes/v1.0/routes_blueprints.js, server/app/routes/v1.0/routes_config_data.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/routes/v1.0/routes_organizations.js, server/app/routes/v1.0/routes_tasks.js, server/install.js
Implementation of Tagging server list.
Ready for code review.
@kkn 
@Kaushik512
=> Implementation of Tagging server list

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
=> Changed API 

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js
=> Changed the blueprint launch .

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParams.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js
=> Tag server position changed

client/cat3/main.html, client/cat3/src/factory/chefDataFormatterService.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEvent.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEventCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, server/app/model/classes/tasks/tasks.js
@udeshrl : Please review and merge.
=> Scheduler Implemented for Tasks

server/app/model/blueprint/blueprint-types/arm-template-blueprint/arm-template-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/azure-blueprint/azure-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/openstack-blueprint/openstack-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/vmware-blueprint/vmware-blueprint.js, server/app/model/blueprint/blueprint.js, server/app/model/classes/instance/instance.js, server/app/model/classes/masters/cloudprovider/awsCloudProvider.js, server/app/routes/v1.0/routes_provider.js, server/app/services/monitorsService.js
=> added file info in response

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html, client/cat3/src/partials/sections/dashboard/genericServices.js
=> Changed the css

server/app/model/classes/masters/cloudprovider/awsCloudProvider.js, server/app/routes/v1.0/routes_provider.js
=> bug fix for provider list api

server/app/model/classes/instance/instance.js, server/app/model/file-upload/file-upload.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/routes/v1.0/routes_organizations.js, server/app/services/monitorsService.js
monitor support for import by ip instance
fixed file upload issue in case of record doesn't exist
=> monitor support for import by ip instance

client/htmls/private/ajax/Settings/CreateConfigManagement.html, client/htmls/private/ajax/Settings/CreateProviders.html
=> Added monitoring for edit of provider and chef

server/app/model/classes/tasks/taskTypeJenkins.js, server/app/model/classes/tasks/tasks.js, server/app/routes/v1.0/routes_config_data.js, server/app/routes/v1.0/routes_tasks.js, server/app/services/taskService.js, server/install.js
Implemented the parameter passing for bots library.
Ready for code review.
@kkn
=> Implemented the parameter passing for bots library

server/app/model/classes/tasks/taskTypeChef.js, server/app/model/classes/tasks/taskTypeScript.js, server/app/model/classes/tasks/tasks.js, server/app/routes/v1.0/routes_organizations.js, server/app/routes/v1.0/routes_tasks.js
Implemented Bots category types
Ready for code review
@kkn
=> Implemented Bots category types

server/app/model/blueprint/blueprint.js
implemented category list for blueprints
=> implemented category list for blueprints

server/app/model/classes/instance/instance.js, server/app/routes/v1.0/routes_organizations.js
removed monitor from import by ip instance
=> removed monitor from import by ip instance

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistoryCtrl.js
1.Delete API endpoint related changes
2.showing NA for history column for blueprint, hiding add to service delivery check for composite & puppet as we didnt implement for the same.
=> UI changes for bots library.

client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestrationCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, server/app/model/classes/tasks/tasks.js, server/app/routes/v1.0/routes_organizations.js
@udeshrl : Please review and merge.
=> Scheduler implemented for script and jenkins task type

client/htmls/private/ajax/Settings/providerSync.html, client/htmls/public/js/awsRDSDashboard.js, server/app/cronjobs/provider-rds-s3-sync/AWSRDSS3ProviderSync.js, server/app/lib/rds.js, server/app/model/resources/rds-resource.js, server/app/model/track/track.js, server/app/services/resourceService.js
RDS Instances are not listing in catalyst
=> CAT-2474 Fixed

client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/services/blueprintCreateServices.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintInfoCtrl.js, client/htmls/private/ajax/Settings/providerSync.html, client/htmls/public/js/awsRDSDashboard.js, server/app/cronjobs/provider-rds-s3-sync/AWSRDSS3ProviderSync.js, server/app/lib/rds.js, server/app/model/resources/rds-resource.js, server/app/routes/v1.0/routes_azure.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/services/resourceService.js
Design Refactor Implementation and CAT-2474 Fixed
=> Design Refactor Implementation and CAT-2474 Fixed

client/htmls/private/ajax/Settings/CreateConfigManagement.html, client/htmls/private/ajax/Settings/CreateProviders.html, client/htmls/private/ajax/Settings/monitoringServer.html, client/htmls/private/index.html
=> Comments for Monitoring taken care

server/app/cronjobs/instance-sync/instanceSync.js, server/app/cronjobs/provider-rds-s3-sync/AWSRDSS3ProviderSync.js, server/app/model/classes/instance/instance.js, server/app/model/resources/rds-resource.js, server/app/model/resources/s3-resource.js, server/app/routes/v1.0/routes_instances.js, server/app/services/instanceService.js, server/app/services/resourceService.js
=> Instance Scheduler Implementation

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/editParams.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParams.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceImportByIp.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addJenkinsParams.html
=> Resolved CAT-2476,2477 & 2479.

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistoryCtrl.js
=> Added execution time, manual time & saved time fields in orchestration history popup.

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html
=> Added 2 more options Run, UI for bot type in creation of tasks.

client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceImportByIp.html
=> Removed hard coded values for tag server in import by ip & done with API integration for tag server list.

client/cat3/customlib/datetime.js
=> Added date time picker

client/cat3/src/partials/sections/dashboard/popups/controller/scheduleCtrl.js
=> Changed the schedule save function

client/htmls/private/ajax/Settings/CreateConfigManagement.html, client/htmls/private/ajax/Settings/CreateProviders.html, client/htmls/private/ajax/Settings/monitoringServer.html
=> Monitoring Server Changes

client/cat3/customlib/ui-bootstrap-custom-tpls-0.13.4.js, client/cat3/src/partials/sections/dashboard/popups/controller/scheduleCtrl.js, client/cat3/src/partials/sections/dashboard/popups/view/schedule.html
=> Added validation for date

server/app/lib/azure.js, server/app/model/classes/instance/instance.js, server/app/services/instanceService.js
Hi @kkn,
Plz review and merge it.
(Instance schedule should not work when end date and time is over.)
=> CAT-2482 Fixed.

client/cat3/src/partials/sections/dashboard/analytics/controller/capacityCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/capacity.html
=> Changed the capacity as per the API

server/app/cronjobs/instance-sync/instanceSync.js, server/app/model/classes/instance/instance.js, server/app/services/instanceService.js
Hi @kkn,
Plz review and merge it.
(Instance Scheduler is not working for multiple Instances.)
=> CAT-2485 Fixed

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js
=> Resolved issue with chef cookbook attributes are not showing in bots execution.

client/cat3/src/partials/sections/dashboard/design/designServices.js
=> build problem fixed

client/cat3/src/factory/chefDataFormatterService.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js, client/cat3/src/partials/sections/dashboard/design/services/blueprintListServices.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html, client/cat3/src/partials/sections/dashboard/design/view/popups/blueprintCopy.html
=> Implemented Delete of Blueprint,Issues listed by QA

server/app/model/classes/instance/instance.js
added provider name in instanceList api
Implemented Async approach
=> added provider name in instanceList api

client/cat3/src/partials/sections/dashboard/design/aDesignCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js, client/cat3/src/partials/sections/dashboard/design/design.html, client/cat3/src/partials/sections/dashboard/design/view/designListView.html
@udeshrl : Please merge. And resolved CAT-2493,2494
=> Filter fix on the right side,Supported for one org and multiple BU and Proj.Template Type as per the requirement

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/popups/controller/scheduleCtrl.js, client/cat3/src/partials/sections/dashboard/popups/view/schedule.html
=> Schedule new UI

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/design/design.scss, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html, client/cat3/src/partials/sections/dashboard/design/view/designListView.html
=> styling changes

client/cat3/main.html
=> changed breadcrumb symbol

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/popups/controller/scheduleCtrl.js, client/cat3/src/partials/sections/dashboard/popups/view/schedule.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanel.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js
=> view , edit , add is completed for schedule

client/cat3/src/partials/sections/dashboard/popups/controller/scheduleCtrl.js, client/cat3/src/partials/sections/dashboard/popups/view/schedule.html
=> Change Date formet for Schuler:

client/cat3/src/partials/sections/dashboard/design/aDesignCtrl.js, client/cat3/src/partials/sections/dashboard/design/services/blueprintListServices.js
=> Fix for docker Bp Listing

client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js
=> date format

client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpSchedule.html
=> date format changed for schedule

client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js
=> Edit section for scheduler

client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html
=> Bugs fixes

server/app/model/audit-trail/audit-trail.js, server/app/routes/v1.0/routes_audit_trails.js, server/app/services/auditTrailService.js
=> BOTs Summary Implementation

client/cat3/src/partials/sections/dashboard/design/aDesignCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js, client/cat3/src/partials/sections/dashboard/design/design.html, client/cat3/src/partials/sections/dashboard/design/design.scss, client/cat3/src/partials/sections/dashboard/design/services/blueprintListServices.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html, client/cat3/src/partials/sections/dashboard/genericServices.js, client/cat3/src/partials/sections/dashboard/popups/controller/orchestrationUpdateChefRunlistCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
=> Resolved QA Bugs and changed UI grid Structure

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/popups/view/schedule.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpSchedule.html
=> Removed the condition of 1st row 

client/cat3/src/partials/sections/dashboard/popups/controller/scheduleCtrl.js
=> one card select

client/cat3/src/partials/sections/dashboard/popups/controller/scheduleCtrl.js, client/cat3/src/partials/sections/dashboard/popups/view/schedule.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpSchedule.html
=> Added validation for day select in schedule 

client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botLogsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/botLogs.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html
=> Bots Audit trail changes, bots summary page UI modifications.

server/app/lib/utils/masterUtil.js, server/app/routes/v1.0/routes_organizations.js, server/app/routes/v1.0/routes_providercommon.js
Installing sensu client for provider import and import by ip
=> Installing sensu client for provider import and import by ip

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, server/app/services/auditTrailService.js, server/app/services/instanceService.js
=> CAT-2528 and CAT-2529 Fixed

client/cat3/main.html, client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botLogsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistoryCtrl.js
This PR contains following things:
1. Bots Summary UI changes 
2. Added icons for status in audit trail page
3. Added icons to differentiate task & blueprint in audit trail page
4. UI fixes in New Task Page
5. Added saved time as NA for executions which are failed
=> Bots Summary UI, UI enhancements. 

server/app/app.js, server/app/cronjobs/catalyst-scheduler/catalystScheduler.js, server/app/lib/utils/apiUtil.js, server/app/model/classes/tasks/tasks.js, server/app/routes/v1.0/routes_organizations.js, server/app/routes/v1.0/routes_tasks.js, server/app/services/blueprintService.js, server/app/services/schedulerService.js, server/app/services/taskService.js
=> Task Scheduler Implementation

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
=> UI enhancements for BOTs

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEventCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
=> Changes for task scheduler

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEventCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
=> Removed one condition and added task for jenkins

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, server/app/model/classes/tasks/tasks.js, server/app/routes/v1.0/routes_organizations.js, server/app/routes/v1.0/routes_tasks.js
=> CAT-2533 Fixed

client/cat3/src/partials/sections/dashboard/bots/botsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
=> bots running & failed page refresh issue when deleting a bot.

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEventCtrl.js
=> Fixed issue with schedule edit for task.

client/cat3/src/factory/workzoneServices.js
=> Changed query param for monitorId

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEvent.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEventCtrl.js, server/app/services/taskService.js
=> Scheduler is not working for Jenkins job(CAT-2534)

client/htmls/private/ajax/Settings/providerSync.html
=> Srikanth telemetry

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEventCtrl.js, client/htmls/private/js/scriptList.js, server/app/cronjobs/catalyst-scheduler/catalystScheduler.js, server/app/model/audit-trail/bot-audit-trail.js, server/app/routes/v1.0/routes_blueprints.js, server/app/routes/v1.0/routes_fileUpload.js, server/app/services/auditTrailService.js, server/app/services/taskService.js
Hi @kkn,
Plz review n merge it.
=> Task-Scheduler/Instance-Scheduler/Script-Gallery Issue Solution

client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryTagMappingCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/discoveryTagMapping.html
=> Tag mapping save and update

server/app/app.js, server/app/cronjobs/catalyst-scheduler/catalystScheduler.js, server/app/model/bots/bots.js, server/app/routes/v1.0/routes_blueprints.js, server/app/routes/v1.0/routes_bots.js, server/app/routes/v1.0/routes_tasks.js, server/app/services/blueprintService.js, server/app/services/botsService.js, server/app/services/schedulerService.js, server/app/services/taskService.js
=> BOTs Scheduler and Launch Implementation

client/cat3/src/partials/sections/dashboard/analytics/view/analyticsTreeMenu.html, client/cat3/src/partials/sections/dashboard/analytics/view/discoveryResources.html
=> Hide the resources

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/blueprintLogCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botExecutionLogsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/chefLogCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/audittrail.html, client/cat3/src/partials/sections/dashboard/bots/view/blueprintLog.html, client/cat3/src/partials/sections/dashboard/bots/view/botExecutionLogs.html, client/cat3/src/partials/sections/dashboard/bots/view/botHistoryLogs.html, client/cat3/src/partials/sections/dashboard/bots/view/botInfo.html, client/cat3/src/partials/sections/dashboard/bots/view/editParams.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceLogs.html, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceLogsCtrl.js
=> Bot UI changes & Bot Blueprint Logs related changes.

client/cat3/src/partials/sections/dashboard/bots/controller/chefLogCtrl.js
=> Resolve UI error for PROD Build

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html
=> Resolved CAT-2575 & CAT-2577.

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, server/app/cronjobs/catalyst-scheduler/catalystScheduler.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/model/bots/bots.js, server/app/model/classes/tasks/tasks.js, server/app/routes/v1.0/routes_bots.js, server/app/services/botsService.js, server/app/services/schedulerService.js, server/app/services/taskService.js, server/install.js
=> Resolved BOTs Issue

client/cat3/src/main.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/analyticsTreeMenu.html, client/cat3/src/partials/sections/dashboard/analytics/view/discoveryResources.html, client/cat3/src/partials/sections/dashboard/genericServices.js
=> inline edit for instance

client/htmls/private/ajax/Settings/CreateBitbucketConfig.html, client/htmls/private/ajax/Settings/CreateFunctionalTestConfig.html, client/htmls/private/ajax/Settings/CreateJiraConfig.html, client/htmls/private/ajax/Settings/CreateOctopusConfig.html, client/htmls/private/ajax/Settings/bitBucketConfigList.html, client/htmls/private/ajax/Settings/functionalTestConfigList.html, client/htmls/private/ajax/Settings/jiraConfigList.html, client/htmls/private/ajax/Settings/octopusConfigList.html, client/htmls/private/index.html, server/app/lib/utils/masterUtil.js, server/app/model/d4dmasters/configmgmt.js, server/app/model/d4dmasters/d4dmastersmodelnew.js, server/app/routes/v1.0/routes_d4dMastersCICD.js
=> New sections added under Devops

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/editParams.html
@udeshrl , Please review and merge the changes.
=> Resolved QA issue.

client/cat3/src/partials/sections/dashboard/analytics/analytics.scss, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryTagMappingCtrl.js, client/htmls/private/ajax/Settings/ProvidersList.html
=> css changed , remove the tag mapping from setting

server/app/db-script/bots-model.js, server/app/services/taskService.js
Hi @kkn,
Pls review and merge it.
=> Create DB Migration Script of BOTs

client/cat3/src/partials/sections/dashboard/analytics/analytics.scss, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js
=> Assigned resources

client/cat3/src/partials/global.scss, client/cat3/src/partials/globals/header/headerDashboard.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analytics.scss, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryTagMappingCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/discoveryResources.html, client/cat3/src/partials/sections/dashboard/analytics/view/instanceManage.html, client/htmls/private/index.html
=> discovery new features added

client/htmls/private/ajax/Settings/CreateNexusServer.html
@udeshrl , @hrushikesh07 : Please merge
=> Resolved CAT-2519,2556

client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js
=> cost big fixed:

server/app/cronjobs/provider-rds-s3-sync/AWSRDSS3ProviderSync.js, server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/model/unmanaged-instance/unmanaged-instance.js
Hi @kkn,
Plz review and merge it.
=> CAT-2605 Fixed

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/editParams.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addScriptParams.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/htmls/private/ajax/Settings/scriptList.html, server/app/model/classes/tasks/taskTypeScript.js, server/app/model/classes/tasks/tasks.js, server/app/model/github/github.js, server/app/routes/v1.0/routes_bots.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/routes/v1.0/routes_github.js, server/app/routes/v1.0/routes_tasks.js, server/app/services/botsService.js, server/app/services/gitHubService.js
=> BOTs Implementation

server/app/routes/v1.0/routes_chef.js
=> fixed sensu cookbook install issue for chef import

client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/instanceManage.html
@udeshrl : Please check and merge.
=> added monitor in cloud

client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js
=> chenged the json

client/cat3/src/partials/sections/dashboard/design/services/blueprintCreateServices.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/services/botsService.js, server/app/services/schedulerService.js
Hi @kkn,
Please check and merge it.
=> CAT-2615 Fixed

client/htmls/private/ajax/Settings/githubList.html, client/htmls/private/index.html
=> Integration of GitHub in settings

client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryTagMappingCtrl.js
=> message changed

client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryTagMappingCtrl.js
=> Confirm box added for edit tag value

server/app/model/github/github.js, server/app/routes/v1.0/routes_github.js, server/app/services/gitHubService.js, server/app/validators/gitHubValidator.js, server/install.js, server/package.json, server/test/routes/testInstances.js
=> GIT-REPO-SYNC Implementation

client/htmls/private/ajax/Settings/githubList.html, client/htmls/private/css/catalyst.css, client/htmls/private/js/gitHubList.js
=> Added a Spinner for Git Clone

client/htmls/private/ajax/Settings/githubList.html, client/htmls/private/js/gitHubList.js, server/app/model/github/github.js, server/app/services/gitHubService.js, server/app/validators/gitHubValidator.js
=> GitHub Changes. Introduced Token 

client/htmls/private/ajax/Settings/CreateProductGroup.html, server/app/model/d4dmasters/d4dmastersmodelnew.js
=> plan cost in business group

client/cat3/src/partials/sections/dashboard/analytics/controller/capacityReportCtrl.js, client/htmls/private/ajax/Settings/providerSync.html, client/htmls/public/js/awsCapacity.js, client/htmls/public/js/awsRDSDashboard.js, client/htmls/public/js/awsS3Dashboard.js
=> Change API End-Point for FilterBy

client/cat3/src/partials/sections/dashboard/analytics/analytics.js, client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js
=> split up select box value changed

client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/htmls/private/ajax/Settings/CreateDockerTemplates.html, client/htmls/private/ajax/Settings/CreateEnvironmentConcept.html, client/htmls/private/ajax/Settings/CreateNexusServer.html
@udeshrl : please review and merge.
=> Check for null -monitorId

client/cat3/src/partials/sections/dashboard/analytics/analytics.js, client/cat3/src/partials/sections/dashboard/analytics/controller/capacityReportCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/capacityReport.html, client/cat3/src/partials/sections/dashboard/analytics/view/cost.html
=> big fixed CAT-2640,CAT-2641,CAT-2642

client/cat3/src/partials/sections/dashboard/analytics/controller/capacityReportCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js
=> API end point changed

client/cat3/src/partials/sections/dashboard/analytics/controller/capacityReportCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/discoverySyncResultCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryTagMappingCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/usageCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botChefLogCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEventCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
=> Resolved JShint errors.

server/app/lib/utils/apiUtil.js, server/app/model/bots/bots.js, server/app/routes/v1.0/routes_audit_trails.js, server/app/services/auditTrailService.js, server/app/services/botsService.js
=> Create generic FilterBy and implement in BOTs

client/cat3/src/partials/sections/dashboard/analytics/analytics.html, client/cat3/src/partials/sections/dashboard/analytics/analyticsServices.js, client/cat3/src/partials/sections/dashboard/analytics/controller/capacityReportCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js
=> week date added

client/cat3/src/partials/sections/dashboard/analytics/analyticsServices.js
=> select current week

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html
=> Added clear button in filter section, added section to show selected filters.

client/cat3/src/partials/sections/dashboard/analytics/controller/capacityReportCtrl.js
=> bg name added in instance list

client/cat3/src/partials/sections/dashboard/bots/controller/botChefLogCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botLogsCtrl.js, server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js, server/app/services/settingsService.js
=> CAT-2648/CAT-2649 Fixed

client/cat3/src/partials/sections/dashboard/analytics/controller/capacityReportCtrl.js
=> Added month name in cost field

server/app/cronjobs/task-sync/taskSync.js, server/app/model/bots/bots.js, server/app/services/blueprintService.js, server/app/services/taskService.js
=> Add LastRunTime field for BOTs

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/botHistory.html
=> Last Run added in bots list, sorting as per last run and history pagination modified

server/app/lib/utils/providerUtil.js, server/app/model/bots/bots.js, server/app/model/classes/masters/cloudprovider/keyPair.js, server/app/model/entity-capacity/entity-capacity.js, server/app/model/entity-costs/entity-costs.js, server/app/model/resource-costs/resource-costs.js, server/app/services/instanceService.js
=> Remove entity-cost/capacity/resource based on removing providers

client/cat3/src/partials/sections/dashboard/analytics/controller/capacityReportCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/capacityReport.html, client/cat3/src/partials/sections/dashboard/analytics/view/cost.html, client/cat3/src/partials/sections/dashboard/analytics/view/discoveryTagMapping.html, client/cat3/src/partials/sections/dashboard/genericServices.js
=> bug fix , error message changed .

server/app/model/resource-costs/resource-costs.js
=> Provider Delete Issue

server/app/routes/v1.0/routes_d4dMastersCICD.js
=> Parsing JIRA Response for JIRA Key

client/cat3/src/partials/sections/dashboard/analytics/controller/usageCtrl.js, client/cat3/src/partials/sections/dashboard/analytics/view/capacityReport.html, client/cat3/src/partials/sections/dashboard/analytics/view/cost.html
=> Size added for usage

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/htmls/private/ajax/Settings/CreateJenkinsConfig.html, client/htmls/private/ajax/Settings/CreateJiraConfig.html, client/htmls/private/ajax/Settings/jiraConfigList.html, server/app/model/d4dmasters/d4dmastersmodelnew.js
=> Bugs for Devops Roles in Settings

server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js
=> Add CFT Stack Message in logs

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
=> Resolved issue with blueprint logs.

server/app/lib/utils/apiUtil.js, server/app/model/cloud-formation/cloud-formation.js, server/app/routes/v1.0/routes_cloudformation.js
=> Add FilterBy API for Cloud Formation and implement Case Sensitive Search 

server/app/model/monitors/monitors.js, server/app/routes/v1.0/routes_monitors.js, server/app/services/monitorsService.js
Added default field in monitors
=> Default monitor organization level

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/botDescriptionCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botScheduleCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/tabs/param.html, client/cat3/src/partials/sections/dashboard/bots/tabs/report.html, client/cat3/src/partials/sections/dashboard/bots/tabs/schedule.html, client/cat3/src/partials/sections/dashboard/bots/view/botHistory.html, client/cat3/src/partials/sections/dashboard/bots/view/botInfo.html, client/cat3/src/partials/sections/dashboard/bots/view/botsDescription.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/cat3/src/partials/sections/dashboard/genericServices.js, server/app/lib/utils/apiUtil.js
=> Changes for BOTS

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/botHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/audittrail.html, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html
=> Changes for category type for blueprint, Firefox issues resolved

server/app/model/bots/1.0/bots.js, server/app/services/botsService.js
=> Added SavedTime per BOTs field

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/botHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/tabs/report.html, client/cat3/src/partials/sections/dashboard/bots/view/botHistory.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html, server/app/model/bots/1.0/bots.js, server/app/services/botsService.js
@udeshrl :
a) Bot history issue resolved, catrgory wise filter click on the cards.
b) Reverted back code for bots(server side)
=> Bots Bugs Resolved 

client/cat3/src/partials/sections/dashboard/bots/controller/botHistoryCtrl.js
=> Added toastr

client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParams.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js
@udeshrl 
@hrushikesh07 
Changed the tag addition functionality to include custom tag value addition.
=> Topic cat 2651

client/cat3/src/partials/sections/dashboard/bots/view/botHistory.html
=> Bot History Name changed

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
=> Dev update with Stage

server/app/db-script/auditTrail-update.js, server/app/services/botsService.js
=> Migration Script for BOTs

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
@udeshrl : Please merge.
[CAT-2681](https://relevancelab.atlassian.net/browse/CAT-2681)
=> Merging Stage code with Dev

client/cat3/src/partials/sections/dashboard/bots/controller/botHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html, server/app/routes/v1.0/routes_bots.js, server/app/services/auditTrailService.js, server/app/services/botsService.js
=> CAT-2682 Implementation

client/htmls/private/ajax/Settings/CICDDashboard.html, client/htmls/private/ajax/Settings/CreateCICDDashboard.html, client/htmls/private/index.html
=> Added New HTML pages for CI/CD Dashboard Listing & Create new CI/CD Dashboard

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/dashboardCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzoneCtrl.js, server/app/routes/v1.0/routes_organizations.js
Workzone retain state
made bot as landing state
@amanpatial please review and merge
=> Workzone retain state

server/app/model/classes/masters/cloudprovider/azureCloudProvider.js, server/app/model/classes/masters/cloudprovider/hppublicCloudProvider.js, server/app/model/classes/masters/cloudprovider/openstackCloudProvider.js
=> Provider's Pem Files Save Issue Resolved

server/app/routes/v1.0/routes.js, server/app/routes/v1.0/routes_dashboardcicd.js
Included wrapper routes for CI CD dashboard this would be used by the dashboard configuration in settings
=> Included wrapper routes for CI CD dashboard

server/app/routes/v1.0/routes_bots.js
=> Maninew service delivery

client/htmls/private/ajax/Settings/CreateCICDDashboard.html
=> Changed CICD page

server/app/routes/v1.0/routes_bots.js, server/app/services/botsService.js
=> modified bots list api

server/app/model/bots/1.1/botsDao.js, server/app/services/botsNewService.js
=> created last run time

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/dashboardCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/workzoneCtrl.js, client/htmls/private/ajax/Settings/CreateCICDDashboard.html, server/app/model/classes/masters/cloudprovider/azureCloudProvider.js, server/app/model/classes/masters/cloudprovider/hppublicCloudProvider.js, server/app/model/classes/masters/cloudprovider/openstackCloudProvider.js, server/app/routes/v1.0/routes.js, server/app/routes/v1.0/routes_d4dMastersCICD.js, server/app/routes/v1.0/routes_dashboardcicd.js, server/app/routes/v1.0/routes_organizations.js
@udeshrl 
CAT-2694
Settings - CI - CD Dashboard :--- API integration for Creation dashboard
=> Creating a new dashboard for jira 

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprintCtrl.js
@hrushikesh07 : please merge.
CAT-2699 resolved
=> Resolved CAT-2699 for composite blueprints

client/htmls/private/ajax/Settings/CreateCICDDashboard.html
Completed edit of CICD Dashboard. Issues pending are,
1. Org, BU and Project Selection validation.
2. Required warning mesage.
3. All round testing.
=> Completed edit of CICD Dashboard

client/htmls/private/ajax/Settings/CreateCICDDashboard.html
@amanpatial 
i  have added  Validation for org, bu, project , dashboard URL, dashboard Name in CICD dashboard config(setting )
=> Added Validation for org, bu, project , dashboardURL, dashboard Name

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, server/app/services/botsNewService.js
=> Implement Sorting for Last Run Time

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/bots/controller/botsExecutionLogsNewCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/botExecutionLogs.html, server/app/engine/bots/executor.js
=> Implemented Polling and executor changes

server/app/engine/bots/executor.js
=> Added a new line in logs

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/botHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botsExecutionLogsNewCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/botsDescription.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/htmls/private/ajax/Settings/githubList.html, client/htmls/private/css/catalyst.css, client/htmls/private/index.html, client/htmls/private/js/gitHubList.js, server/app/db-script/auditTrail-update.js, server/app/db-script/bots-model.js, server/app/db-script/install.js, server/app/db-script/instance-update.js, server/app/db-script/monitor-update.js, server/app/db-script/remove-task-history.js, server/app/db-script/task-history-update.js, server/app/engine/bots/executor.js, server/app/model/file-upload/file-upload.js, server/app/routes/v1.0/routes_botsNew.js
@Graha : Please merge
CAT - [2717](https://relevancelab.atlassian.net/browse/CAT-2717)
=> Github UI Changes along with UI improvements in Bots

client/htmls/private/js/gitHubList.js, client/htmls/private/js/scriptList.js, server/app/model/github/github.js, server/app/services/botsNewService.js, server/app/services/gitHubService.js, server/install.js, server/package.json
=> Replace Nodegit with Github API for GITHUB Sync

client/htmls/private/ajax/Settings/CreateCICDDashboard.html, server/app/model/cicd-dashboards/cicdDashboad.js, server/app/routes/v1.0/routes_cicddashboardserver.js, server/app/services/cicdDashboardService.js, server/app/validators/cicdDashboardServerValidator.js
Fixed Dashboard save issue. The form ID was altered during last merge.
=> Fixed Dashboard save issue

client/cat3/src/partials/sections/dashboard/bots/controller/botScheduleCtrl.js, server/app/app.js, server/app/cronjobs/catalyst-scheduler/catalystScheduler.js, server/app/engine/bots/executor.js, server/app/services/botsNewService.js, server/app/services/schedulerService.js
=> Resolved BOTs Scheduler Issue and GIT Hub Sync Issue

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/bots/controller/botDescriptionCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botScheduleCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/tabs/schedule.html, client/cat3/src/partials/sections/dashboard/bots/view/botSchedule.html, client/htmls/private/js/gitHubList.js
@Graha : Please merge
Additional Changes :
a) Changed the token type to be password on edit.
=> Resolved CAT -2722

server/app/services/gitHubService.js, server/install.js
=> Change GitHub Download and Extract Path

server/app/model/bots/1.1/botsDao.js, server/app/routes/v1.0/routes_botsNew.js, server/app/services/botsNewService.js, server/install.js
=> Add delete Functionality in New BOTs model

client/htmls/private/ajax/Settings/CreateCICDDashboard.html
@amanpatial : Please merge.
a) Filters for BG and Project resolved. On Edit also the values are retained and user can change the selection.
=> Resolved CAT-2791

client/cat3/src/partials/sections/dashboard/bots/bots.scss
=> Resolved Bots Card Alignment Issue

client/htmls/private/ajax/Settings/cicddashboardserverList.html, client/htmls/private/index.html, client/htmls/private/js/cicddashboardserver.js, server/app/model/cicd-dashboards/cicdDashboard.js, server/app/services/cicdDashboardService.js
Added CICD Dashboard Server Setting as part of the autocreate dashboard design change.
=> Added CICD Dashboard Server Setting

client/cat3/src/partials/sections/dashboard/bots/bots.scss
=> Width for Bot Card Changed

client/htmls/private/ajax/Settings/CreateCICDDashboard.html, client/htmls/private/ajax/Settings/cicddashboardserverList.html, client/htmls/private/js/cicddashboardserver.js, server/app/lib/utils/masterUtil.js, server/app/model/cicd-dashboards/cicdDashboard.js, server/app/model/d4dmasters/d4dmastersmodelnew.js, server/app/routes/v1.0/routes_cicddashboardserver.js, server/app/routes/v1.0/routes_d4dMastersCICD.js, server/app/routes/v1.0/routes_dashboardcicd.js, server/app/services/cicdDashboardService.js
Completed Dashboard configurations sections. Pending restart service to be integrated into save.
=> Completed Dashboard configurations sections

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/editParams.html, client/cat3/src/partials/sections/dashboard/genericServices.js
=> Resolved CAT-2794

client/cat3/src/partials/sections/dashboard/genericServices.js
=> Authentication  added for service (API)

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/bots/botsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botDescriptionCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/tabs/editParams.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html
=> BOTs UX and program review.  ## CAT-2735

client/htmls/private/ajax/Settings/cicddashboardserverList.html, client/htmls/private/js/cicddashboardserver.js, server/app/routes/v1.0/routes_cicddashboardserver.js, server/app/services/cicdDashboardService.js
Fixed catalyst username not loading issue on dashboard server addition screen
=> fixed catalyst username not loading issue

client/htmls/private/ajax/Settings/githubList.html, client/htmls/private/js/gitHubList.js
UI completed for showing the new bots. API integration required for bulk import
=> Git Sync and Import - CAT 2830

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/editParams.html
@Graha : Resolved CAT-2840. Please merge
=> Topic stage

client/cat3/poc/servicenow/servicenow-bot.html
=> Service now bot API added

server/app/model/github/githubTemp.js, server/app/model/push-notice/push-notice.js, server/app/routes/v1.0/routes_botsNew.js, server/app/routes/v1.0/routes_github.js, server/app/services/gitHubService.js, server/app/services/noticeService.js
@Graha @Durgesh1988  Review code and merge it
=> Git Import and git single bot sync

server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/services/botsNewService.js, server/app/services/gitHubService.js
=> Add Notification for Blueprint Executor/GitHub Issue

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/tabs/editParams.html, client/cat3/src/partials/sections/dashboard/bots/view/audittrail.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/cat3/src/partials/sections/dashboard/bots/view/newBotCreate.html, client/htmls/private/ajax/Settings/botEngineList.html, client/htmls/private/ajax/Settings/createBotEngine.html, client/htmls/private/ajax/Settings/githubList.html, client/htmls/private/css/catalyst.css, client/htmls/private/index.html, client/htmls/private/js/gitHubList.js, client/htmls/private/js/settingscommon.js, server/app/lib/utils/masterUtil.js, server/app/model/d4dmasters/configmgmt.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/routes/v1.0/routes_github.js, server/app/services/botsNewService.js, server/app/services/gitHubService.js
=> CAT 2819,2735, Addition of Bot Engine in Settings

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/htmls/private/ajax/Settings/botEngineList.html, client/htmls/private/ajax/Settings/createBotEngine.html, server/app/engine/bots/chefExecutor.js, server/app/engine/bots/scriptExecutor.js, server/app/lib/utils/masterUtil.js, server/app/routes/v1.0/routes_botsNew.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/services/botsNewService.js, server/app/services/gitHubService.js
=> Implemented BOTs Engine Remote Server and Resolved Issues of GitHub and BOTs

client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/audittrail.html, client/htmls/private/ajax/Settings/cicddashboardserverList.html, client/htmls/private/index.html, client/htmls/private/js/cicddashboardserver.js
=> CICD dashboard bug fixed

client/cat3/src/partials/sections/dashboard/bots/controller/newBotCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/cat3/src/partials/sections/dashboard/bots/view/newBotCreate.html, client/htmls/private/index.html, server/app/cronjobs/task-sync/taskSync.js, server/app/engine/bots/chefExecutor.js, server/app/engine/bots/scriptExecutor.js, server/app/model/bots/1.1/botsDao.js, server/app/routes/v1.0/routes_botsNew.js, server/app/routes/v1.0/routes_fileUpload.js, server/app/services/botsNewService.js, server/app/services/botsService.js
=> Added BOTS Creation  Functionality via Catalyst

client/htmls/private/ajax/Settings/createBotEngine.html, client/htmls/private/js/gitHubList.js
@hrushikesh07 : Please merge.
CAT - 2862
=> Removed IP Validation for Bot Engine

server/app/model/push-notice/push-notice.js, server/app/routes/v1.0/routes_notice.js, server/app/services/botsNewService.js, server/app/services/gitHubService.js, server/app/services/noticeService.js, server/install.js, server/package.json
=>  	New API for Notification and GIT Hub Changes

client/cat3/src/partials/sections/dashboard/bots/controller/botDescriptionCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/newBotCtrl.js, client/cat3/src/partials/sections/dashboard/bots/tabs/editParams.html, client/cat3/src/partials/sections/dashboard/bots/view/botsDescription.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/cat3/src/partials/sections/dashboard/bots/view/newBotCreate.html, server/app/services/botsNewService.js
=> Resolved CAT- 2865

server/app/routes/v1.0/routes_github.js, server/app/services/gitHubService.js
=> Modified single bot sync

client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botScheduleCtrl.js, client/cat3/src/partials/sections/dashboard/bots/tabs/editParams.html, client/cat3/src/partials/sections/dashboard/bots/tabs/schedule.html
@amanpatial : Please review and merge. These are the Bugs raised by Jagadeesh.
CAT - 2874, CAT - 2873, CAT - 2871, CAT - 2867( Schedule for BOTs)
=> Resolved BOTS Bugs

server/app/engine/bots/chefExecutor.js, server/app/engine/bots/scriptExecutor.js, server/app/routes/v1.0/routes_github.js, server/app/services/botsNewService.js, server/app/services/gitHubService.js, server/app/services/schedulerService.js, server/package.json
=> Add Timer Counter for Fetching Audit Trails from BOTEngine Server

server/app/engine/bots/blueprintExecutor.js, server/app/engine/bots/chefExecutor.js, server/app/engine/bots/scriptExecutor.js, server/app/lib/chef.js, server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/azure-blueprint/azure-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/openstack-blueprint/openstack-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/vmware-blueprint/vmware-blueprint.js, server/app/model/blueprint/blueprint.js, server/app/routes/v1.0/routes_blueprints.js, server/app/routes/v1.0/routes_providercommon.js, server/app/services/blueprintService.js
=> Provider Sync Issue and BOTs Issue and new API for Blueprint List

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/services/botsCreateService.js, client/cat3/src/partials/sections/dashboard/bots/tabs/editParams.html, client/cat3/src/partials/sections/dashboard/bots/tabs/report.html, client/cat3/src/partials/sections/dashboard/bots/view/botsDescription.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/htmls/private/ajax/Settings/botEngineList.html, client/htmls/private/ajax/Settings/createBotEngine.html, client/htmls/private/index.html
=> BOTs UI issues   CAT -2870

client/cat3/main.html, client/cat3/src/clientRoutes.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/bots/controller/botScheduleCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/instanceInfoCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/newBotCtrl.js, client/cat3/src/partials/sections/dashboard/bots/services/botsCreateService.js, client/cat3/src/partials/sections/dashboard/dashboardCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/createCompositeCtrl.js, client/cat3/src/partials/sections/dashboard/genericServices.js, client/cat3/src/partials/sections/dashboard/popups/controller/orchestrationUpdateChefRunlistCtrl.js, client/cat3/src/partials/sections/dashboard/setting/asettingCtrl.js, client/cat3/src/partials/sections/dashboard/setting/controller/createDashboard.js, client/cat3/src/partials/sections/dashboard/track/trackCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, client/cat3/src/partials/sections/login/loginCtrl.js
@amanpatial 
jshint error fixed .
=> Demo page with jshint error fixed .

client/cat3/main.html, client/cat3/src/clientRoutes.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/botScheduleCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/instanceInfoCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/newBotCtrl.js, client/cat3/src/partials/sections/dashboard/bots/services/botsCreateService.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/cat3/src/partials/sections/dashboard/dashboardCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js, client/cat3/src/partials/sections/dashboard/design/controllers/createCompositeCtrl.js, client/cat3/src/partials/sections/dashboard/genericServices.js, client/cat3/src/partials/sections/dashboard/popups/controller/orchestrationUpdateChefRunlistCtrl.js, client/cat3/src/partials/sections/dashboard/setting/asettingCtrl.js, client/cat3/src/partials/sections/dashboard/setting/controller/createDashboard.js, client/cat3/src/partials/sections/dashboard/track/trackCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpActionHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js, client/cat3/src/partials/sections/login/loginCtrl.js, server/app/services/botsNewService.js
=> CAT - 2889. Issues Related to Bots

client/cat3/main.html, client/cat3/src/clientRoutes.js, client/cat3/src/partials/sections/dashboard/dashboardCtrl.js
=> Prod Build Failure Resolved

client/cat3/main.html, client/cat3/src/clientRoutes.js, client/cat3/src/partials/sections/dashboard/dashboardCtrl.js
@amanpatial : Please merge.
CAT - 2891
=> Resolved Prod Build Failure

client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html, client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js, server/app/app.js, server/app/lib/chef.js, server/app/model/azure-arm/azure-arm.js, server/app/model/blueprint/blueprint-types/arm-template-blueprint/arm-template-blueprint.js, server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/model/classes/instance/instance.js, server/app/model/cloud-formation/cloud-formation.js, server/app/model/resourceMap/resourceMap.js, server/app/model/resources/base-resources.js, server/app/model/resources/resources.js, server/app/routes/v1.0/routes.js, server/app/routes/v1.0/routes_arm.js, server/app/routes/v1.0/routes_blueprints.js, server/app/routes/v1.0/routes_cloudformation.js, server/app/routes/v1.0/routes_instances.js, server/app/routes/v1.0/routes_organizations.js, server/app/routes/v1.0/routes_providercommon.js, server/app/routes/v1.0/routes_resourceMap.js, server/app/routes/v1.0/routes_resources.js, server/app/routes/v1.0/routes_serviceMap.js, server/app/services/auditTrailService.js, server/app/services/blueprintService.js, server/app/services/resourceMapService.js, server/app/services/resourceService.js, server/app/services/serviceMapService.js
=> Resolved ProviderSync Issue,New Route/Service/Model for ResourceMap,Resolved CFT Launch Issue and StackName check

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/botDescriptionCtrl.js, client/cat3/src/partials/sections/dashboard/bots/tabs/help.html, client/cat3/src/partials/sections/dashboard/bots/view/botsDescription.html, client/cat3/src/partials/sections/dashboard/bots/view/botsDetail.html, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js, client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html
=> CAT- 2893 & Cookbook Issue for CFT

server/app/model/resourceMap/resourceMap.js, server/app/routes/v1.0/routes_bots.js, server/app/routes/v1.0/routes_botsNew.js, server/app/services/blueprintService.js, server/app/services/resourceMapService.js, server/app/services/resourceService.js, server/install.js
=> Add Pagination in resourceMap

server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/lib/azure-arm.js, server/app/lib/utils/apiUtil.js, server/app/model/blueprint/blueprint-types/arm-template-blueprint/arm-template-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/azure-blueprint/azure-blueprint.js, server/app/model/blueprint/blueprint.js, server/app/model/classes/instance/instance.js, server/app/model/classes/masters/cloudprovider/azureCloudProvider.js, server/app/model/docker.js, server/app/routes/v1.0/routes_arm.js, server/app/routes/v1.0/routes_azure.js, server/app/routes/v1.0/routes_fileUpload.js, server/app/routes/v1.0/routes_instances.js, server/app/routes/v1.0/routes_provider.js, server/app/services/resourceMapService.js, server/app/services/resourceService.js
=> Resolved Azure Provider File Upload Issue and Launch Issue

client/htmls/private/ajax/Settings/chefSync.html, client/htmls/private/ajax/Settings/providerSync.html, client/htmls/private/js/gitHubList.js, client/htmls/private/js/scriptList.js, client/htmls/public/js/awsCapacity.js, client/htmls/public/js/awsRDSDashboard.js, client/htmls/public/js/awsS3Dashboard.js, client/htmls/public/js/dashboard.js, server/app/lib/utils/apiUtil.js, server/app/model/resourceMap/resourceMap.js, server/app/routes/v1.0/routes_resourceMap.js, server/app/services/resourceMapService.js
=> Resolved Datatable issue and ResouceMap Changes

client/cat3/src/partials/sections/dashboard/bots/controller/botDescriptionCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/botsDescription.html
=> CAT - 2919 for Service Now

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/tabs/editParams.html, client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js
@Graha : Please merge.
CAT - 2908, CAT - 2920
=> Resolved Runlist Issue for CFT and ARM & Chef Exec on Local

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
=> Resolved Few points for Bots UI

server/app/cronjobs/catalyst-scheduler/catalystScheduler.js, server/app/engine/bots/blueprintExecutor.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/services/organizationService.js
=>  	Resolved blueprint Launch Issue and saved time issue

server/app/config/global-data.js, server/app/cronjobs/catalyst-scheduler/catalystScheduler.js, server/app/engine/bots/chefExecutor.js, server/app/engine/bots/scriptExecutor.js, server/install.js
@Graha @Durgesh1988  please review and merge
=> Added request time in audit update

client/cat3/main.html, client/cat3/src/partials/sections/dashboard/bots/controller/botScheduleCtrl.js, client/cat3/src/partials/sections/dashboard/bots/tabs/schedule.html
=> Resolved CAT - 2922

server/app/app.js, server/app/model/blueprint/blueprint-types/arm-template-blueprint/arm-template-blueprint.js, server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/services/botService.js, server/app/services/schedulerService.js
=> CAT-2916/CAT-2917/CAT-2918 Fixed

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/newBotCtrl.js, client/cat3/src/partials/sections/dashboard/bots/services/botsCreateService.js, client/cat3/src/partials/sections/dashboard/bots/tabs/editParams.html, client/cat3/src/partials/sections/dashboard/bots/view/newBotCreate.html, client/cat3/src/partials/sections/dashboard/genericServices.js, client/cat3/src/partials/sections/dashboard/workzone/orchestration/orchestration.scss, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html, client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
@hrushikesh07 : please merge
CAT - 2941
=> Jenkins & Script BOT Creation - BOTs section

server/app/engine/bots/chefExecutor.js, server/app/engine/bots/scriptExecutor.js
@Graha @Durgesh1988 please review and merge code
=> Fixed BOT engine failed

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/services/botsCreateService.js, client/cat3/src/partials/sections/dashboard/bots/tabs/editParams.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html
@hrushikesh07 : Please merge. CAT - 2940
=> Blueprint launch for BOTs

client/cat3/src/partials/sections/dashboard/bots/controller/newBotCtrl.js, client/cat3/src/partials/sections/dashboard/bots/services/botsCreateService.js, client/cat3/src/partials/sections/dashboard/bots/view/newBotCreate.html
=> Resolved CAT -2941

client/cat3/src/main.js, client/cat3/src/partials/sections/dashboard/bots/controller/botsExecutionLogsNewCtrl.js, server/app/engine/bots/chefExecutor.js, server/app/engine/bots/scriptExecutor.js, server/app/services/noticeService.js, server/app/services/schedulerService.js
@Graha  @Durgesh1988  please review and merge it
=> server push in bots

client/cat3/src/partials/sections/dashboard/bots/view/newBotCreate.html, client/htmls/private/ajax/Settings/scriptList.html, client/htmls/private/js/scriptList.js, server/app/engine/bots/chefExecutor.js, server/app/engine/bots/scriptExecutor.js, server/app/services/commonService.js
=> PowerShell Implementation for BOT and Upload Local files on BOT Engine

server/app/services/settingsService.js
=> Resolved User and Role issue

client/cat3/src/partials/sections/dashboard/bots/view/newBotCreate.html, client/htmls/private/ajax/Settings/scriptList.html, client/htmls/private/js/scriptList.js, server/app/lib/utils/masterUtil.js, server/app/services/botService.js, server/app/services/commonService.js, server/app/services/gitHubService.js, server/app/services/settingsService.js, server/package.json
=> Implement Powershell and Checked heartbeat of BOT Engine

server/app/engine/bots/scriptExecutor.js, server/app/model/bots/1.1/bot.js, server/app/services/auditTrailService.js, server/app/services/botService.js, server/app/services/commonService.js, server/app/services/schedulerService.js
=> Resolved BOTs Issues

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, server/app/model/bots/1.1/bot.js, server/app/routes/v1.0/routes_audit_trails.js, server/app/services/auditTrailService.js, server/app/services/botOldService.js, server/app/services/botService.js, server/package.json
=> Resolved SINTL BOT Issues

server/app/services/commonService.js
=> Resolved YAML Issue for more then one params

client/cat3/src/partials/sections/dashboard/bots/view/library.html
@hrushikesh07 : Please merge
CAT - 2957
=> Removed Time Saved

server/app/model/github/github.js, server/app/model/github/githubTemp.js, server/app/routes/v1.0/routes_github.js, server/app/services/botService.js, server/app/services/gitHubService.js
@Graha @Durgesh1988  please review and merge
=> Github Sync

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/botHistoryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html, server/app/cronjobs/task-sync/taskSync.js, server/app/model/audit-trail/base-audit-trail.js, server/app/services/auditTrailService.js, server/app/services/botOldService.js, server/app/services/botService.js
@Graha : Please merge
CAT - 2958
=> Changes for time saved - BOTs

server/app/services/auditTrailService.js, server/app/services/botService.js
Fixed Few bugs and audit trail changes
=> Org team bot perm

server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/engine/bots/scriptExecutor.js, server/app/model/classes/instance/instance.js, server/app/model/monitors/monitors.js, server/app/model/services/services.js, server/app/routes/v1.0/routes_services.js, server/app/services/serviceMapService.js
=> SAE Implementation

client/cat3/main.html, client/cat3/src/partials/global.scss, client/cat3/src/partials/globals/header/headerDashboard.html, client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/services/controller/servicesAuthenticationCtrl.js, client/cat3/src/partials/sections/dashboard/services/controller/servicesDescriptionCtrl.js, client/cat3/src/partials/sections/dashboard/services/controller/servicesListCtrl.js, client/cat3/src/partials/sections/dashboard/services/popups/serviceAuthentication.html, client/cat3/src/partials/sections/dashboard/services/services.scss, client/cat3/src/partials/sections/dashboard/services/services/servicesCreateService.js, client/cat3/src/partials/sections/dashboard/services/servicesCtrl.js, client/cat3/src/partials/sections/dashboard/services/tabs/resources.html, client/cat3/src/partials/sections/dashboard/services/tabs/serviceInfo.html, client/cat3/src/partials/sections/dashboard/services/tabs/serviceReadme.html, client/cat3/src/partials/sections/dashboard/services/view/servicesCreate.html, client/cat3/src/partials/sections/dashboard/services/view/servicesDescription.html, client/cat3/src/partials/sections/dashboard/services/view/servicesList.html, client/htmls/private/index.html
=> Services Authentication - CRUD

client/htmls/private/js/botList.js
@Graha : Please merge.
CAT - 2959
=> Added team list

client/cat3/src/partials/sections/dashboard/services/controller/servicesAuthenticationCtrl.js, client/cat3/src/partials/sections/dashboard/services/controller/servicesDescriptionCtrl.js, client/cat3/src/partials/sections/dashboard/services/popups/serviceAuthentication.html, client/cat3/src/partials/sections/dashboard/services/services/servicesCreateService.js, server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/lib/chef.js, server/app/model/resources/base-resources.js, server/app/model/resources/instance-resource.js, server/app/model/resources/resources.js, server/app/model/services/services.js, server/app/routes/v1.0/routes_services.js, server/app/services/commonService.js, server/app/services/resourceService.js, server/app/services/serviceMapService.js
=> SAE Impmentation

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/services/botsCreateService.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/htmls/private/ajax/Settings/botTeamList.html, client/htmls/private/index.html, client/htmls/private/js/botList.js, server/app/model/org-resource-permission/orgResourcePermission.js, server/app/routes/v1.0/routes.js, server/app/routes/v1.0/routes_orgResourcePermission.js, server/app/services/auditTrailService.js, server/app/services/botService.js, server/app/services/orgResourcePermissionService.js, server/app/validators/orgResourcePermissionValidator.js
@Graha : Please merge
CAT - 2959
=> Added BOTs Team Relationship

client/cat3/src/main.js, client/cat3/src/partials/globals/breadcrumb/breadcrumbService.js, client/cat3/src/partials/globals/header/headerDashboard.html, client/cat3/src/partials/sections/dashboard/bots/botsCtrl.js, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html, client/cat3/src/partials/sections/dashboard/dashboardCtrl.js, client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js, client/htmls/private/js/botList.js
=> Resolved Bugs for Bots & Team

server/app/cronjobs/chef-sync/chef-sync.js, server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/lib/utils/apiUtil.js, server/app/model/services/services.js, server/app/routes/v1.0/routes_instances.js, server/app/services/commonService.js, server/app/services/serviceMapService.js
Hi @Graha ,
Please review and merge it,
=> SAE Implementation for Tags

client/cat3/src/partials/sections/dashboard/bots/controller/syncCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/sync.html, server/app/engine/bots/scriptExecutor.js, server/app/services/botService.js, server/app/services/gitHubService.js, server/package.json
@Graha @Durgesh1988  please review and merge.
=> Fixed yaml parser and some sync related issues 

server/app/cronjobs/provider-sync/AWSProviderSync.js
=> Chef Group Implementation for SAE

server/app/model/classes/instance/instance.js, server/app/model/resources/resources.js, server/app/model/unassigned-instances/unassigned-instances.js, server/app/model/unmanaged-instance/unmanaged-instance.js, server/app/services/botService.js
=> Added terminated instances in Cloud List

client/cat3/src/factory/workzoneServices.js, client/cat3/src/partials/sections/dashboard/services/controller/servicesDescriptionCtrl.js, client/htmls/private/ajax/Settings/monitoringServer.html, client/htmls/public/awsS3Dashboard.html, client/htmls/public/js/awsS3Dashboard.js, server/app/cronjobs/chef-sync/chef-sync.js, server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/cronjobs/provider-tags-aggregation/ProviderTagsAggregation.js, server/app/engine/bots/blueprintExecutor.js, server/app/lib/s3.js, server/app/lib/utils/apiUtil.js, server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/model/blueprint/blueprint.js, server/app/model/classes/instance/instance.js, server/app/services/blueprintService.js, server/app/services/resourceService.js, server/app/services/saeService.js, server/app/services/serviceMapService.js
=> SAE Implementation for Blueprint Launch

client/cat3/src/partials/sections/dashboard/design/controllers/serviceDescriptionCtrl.js, client/cat3/src/partials/sections/dashboard/services/controller/servicesDescriptionCtrl.js, server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/lib/credentialcryptography.js, server/app/lib/utils/cryptography.js, server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js, server/app/model/resources/resource-types/instance-resource.js, server/app/model/resources/resource-types/rds-resource.js, server/app/model/resources/resource-types/s3-resource.js, server/app/model/resources/resources.js, server/app/routes/v1.0/routes_instances.js, server/app/services/commonService.js, server/app/services/instanceService.js
=> Resolved resources ara not listing in DB issue

server/app/routes/v1.0/routes_resources.js, server/app/services/commonService.js
=> Changes for SAE

server/app/model/d4dmasters/d4dmastersmodelnew.js, server/app/model/services/services.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/services/saeService.js, server/app/services/serviceMapService.js
=> SAE Changes

client/cat3/src/partials/sections/dashboard/design/services/servicesCreateService.js, server/app/services/commonService.js, server/app/services/saeService.js, server/app/services/serviceMapService.js
=> SAE Changes for Monitor

server/app/cronjobs/provider-sync/AWSProviderSync.js
=> SAE Changes for Import By IP

server/app/cronjobs/provider-sync/AWSProviderSync.js, server/app/model/classes/masters/cloudprovider/awsCloudProvider.js, server/app/model/resources/resources.js, server/app/model/v2.0/providers/providers.js, server/app/routes/v1.0/routes_instances.js, server/app/routes/v1.0/routes_jenkins.js, server/app/routes/v1.0/routes_serviceStatus.js, server/app/routes/v1.0/routes_trendUsage.js, server/app/routes/v2.0/blueprints.js, server/app/services/blueprintService.js, server/app/services/compositeBlueprintService.js, server/app/services/saeService.js, server/app/services/schedulerService.js, server/app/services/serviceMapService.js
=> Remove console logs and resolved SAE Issues

server/app/app.js
=> CI/CD Dashboard Testing

client/cat3/src/partials/sections/dashboard/bots/view/library.html
=> BOT library grid view

client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html, server/app/lib/azure-arm.js, server/app/lib/azure.js, server/app/model/blueprint/blueprint-types/arm-template-blueprint/arm-template-blueprint.js, server/app/model/blueprint/blueprint-types/instance-blueprint/azure-blueprint/azure-blueprint.js, server/app/routes/v1.0/routes_arm.js, server/app/services/blueprintService.js
API response updated for ARM deployment deletion.
=> Fixed ARM delete issue

server/app/model/classes/instance/instance.js, server/app/routes/v1.0/routes_instances.js, server/app/services/blueprintService.js
fixed command center addition for arm
=> fixed command center addition

server/app/model/blueprint/blueprint-types/arm-template-blueprint/arm-template-blueprint.js, server/app/services/blueprintService.js, server/install.js
Fixed multi registration in dboard azure arm launch
=> Fixed multi registration in dboard azure arm launch

server/app/services/gitHubService.js
Included bitbucket sync for botengine metadata
=> Included bitbucket sync for botengine metadata

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/serviceNow.json, client/cat3/src/partials/sections/dashboard/bots/view/audittrail.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html, server/app/services/auditTrailService.js
New field and functionality added for unresolved tickets on "failed run" section on both client and server side.
Filters functionality modified accordingly on client side.
=> Failed Run section updated with filters

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/audittrail.html, client/cat3/src/partials/sections/dashboard/bots/view/library.html, server/app/services/auditTrailService.js
Filters for Total runs, Failed Runs,  Ticket resolved in Bots section are implemented.
Transition from Running Bots to Total Runs is completed.
=> C50-399 and C50-422

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html
UI grid Pagination for C50-399 and C50-422 fixed.
Search field fixed.
=> C50-399 and C50-422 updated

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html
Filter functionalities enhanced for Bots section.
=> C50-399 and C50-422 enhanced

client/cat3/catalyst/partials/sections/dashboard/bots/bots.css, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
Bugs fixed C50-437 and C50-438.
=> Enhancements for Bots section- C50-437 and C50-438

client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html
=> C50-453 and C50-438

client/cat3/src/partials/global.scss, client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html
C50-454 and C50-456. Filter and bot section view modified.
=> C50-454 and C50-456

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/library.html, server/app/services/auditTrailService.js
/audit-trail/bot-summary API updated.
=> C50-495 - Bot Summary api  updated

client/cat3/main.html, client/cat3/src/partials/sections/dashboard/bots/bots.scss, client/cat3/src/partials/sections/dashboard/bots/controller/botReportCtrl.js, client/cat3/src/partials/sections/dashboard/bots/view/botreport.html, server/app/routes/v1.0/routes_audit_trails.js, server/app/services/auditTrailService.js
Exporting options for PDF and csv added in Bot Report Module
=> Exporting options for PDF and csv added in Bot Report Module

client/htmls/private/ajax/Settings/createBotEngine.html, server/app/lib/utils/masterUtil.js, server/app/model/d4dmasters/d4dmastersmodelnew.js, server/app/routes/v1.0/routes_d4dMasters.js, server/app/services/botService.js
Reverts RLOpenCatalyst/core#1640
=> Revert "Multiple BOT Executor feature"
