RLOpenCatalyst/core

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistoryCtrl.js
client/htmls/private/ajax/Settings/CreateProviders.html
client/htmls/private/ajax/Settings/DashboardSettings.html
client/htmls/private/ajax/Settings/ImagesList.html
client/htmls/private/ajax/Settings/NexusServerList.html
client/htmls/private/ajax/Settings/cmdbList.html
client/htmls/private/ajax/Settings/videos.html
client/htmls/public/css/Dashboard.css
client/htmls/public/dashing.html
server/app/routes/v1.0/routes_provider.js

Resolved QA Bugs

---

client/htmls/private/ajax/Settings/CreateProviders.html
client/htmls/public/instanceLog.html
client/htmls/public/orchestrationLog.html
server/app/cronjobs/provider-sync/AWSProviderSync.js
server/app/model/blueprint/blueprint-types/arm-template-blueprint/arm-template-blueprint.js
server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js
server/app/model/classes/instance/instance.js
server/app/model/log-trail/instanceLog.js
server/app/model/unassigned-instances/unassigned-instances.js
server/app/model/unmanaged-instance/unmanaged-instance.js
server/app/routes/v1.0/routes_arm.js
server/app/routes/v1.0/routes_audit_trails.js
server/app/routes/v1.0/routes_cloudformation.js
server/app/routes/v1.0/routes_instances.js
server/app/services/instanceService.js

CAT-2268- Unable to save Vmware and Openstack Providers on Editing
CAT-2269 -Unable to save Vmware and Openstack Providers on Editing
CAT-2271 -When user tries to update Azure provider its getting deleted
CAT-2273-Show Terminated Instance details in Audit Trial Instances Page
CAT-2274 -Instance Logs are not matching in Audit trial Logs

CAT-2268,2269,2271,2273 and 2274 Fixed

---

client/htmls/private/ajax/Settings/CreateProviders.html
client/htmls/private/ajax/Settings/providerSync.html
client/htmls/public/js/awsCapacity.js
server/app/model/classes/instance/instance.js
server/app/model/unassigned-instances/unassigned-instances.js
server/app/model/unmanaged-instance/unmanaged-instance.js

CAT-2329(Planned Cost must not be mandatory in Create Providers page)
CAT-2332(Datatable error on navigating to Assigned Section in provider sync)
CAT-2333(IP address is not changing on restarting the instances)		
CAT-2334(user is able to update same tags for BU, Project and Environment)

CAT-2329/2332/2333/2334 Fixed

---

client/htmls/private/ajax/Settings/providerSync.html
client/htmls/public/js/awsCapacity.js

CAT-2340 User should not be able to save when "None" option is selected in Mappings tab	
CAT-2339 Save button should be disabled when no data present in mappings tab	
CAT-2338 Validation message is not showing when user tries to save tags without selecting BG, Project and Environment

CAT-2338/CAT-2339/CAT-2340 Fixed

---

client/htmls/private/ajax/Settings/providerSync.html
client/htmls/public/js/awsCapacity.js

CAT-2332/CAT-2341 fixed

---

server/app/routes/v1.0/routes_serviceStatus.js
server/install.js

Changes done for service controller. Host and Key has been added as a part of app-config

CAT-2179 Fixed

---

client/htmls/private/ajax/Settings/Dashboard.html
client/htmls/private/ajax/Settings/bgWizard.html
client/htmls/private/ajax/Settings/configManagementWizard.html
client/htmls/private/ajax/Settings/devopsRolesWizard.html
client/htmls/private/ajax/Settings/dockerWizard.html
client/htmls/private/ajax/Settings/envWizard.html
client/htmls/private/ajax/Settings/galleryWizard.html
client/htmls/private/ajax/Settings/jenkinsWizard.html
client/htmls/private/ajax/Settings/projWizard.html
client/htmls/private/ajax/Settings/providerWizard.html
client/htmls/private/ajax/Settings/scriptWizard.html
client/htmls/private/ajax/Settings/serviceCommandWizard.html
client/htmls/private/ajax/Settings/settingsWizard.html
client/htmls/private/ajax/Settings/teamWizard.html
client/htmls/private/ajax/Settings/vmImageWizard.html
client/htmls/private/css/wizardBg.css
client/htmls/private/js/settingscommon.js

@udeshrl : Please review and merge . Bugs for Settings wizard resolved.

Topic settings refactor

---

client/htmls/private/ajax/Settings/Dashboard.html
client/htmls/private/ajax/Settings/bgWizard.html
client/htmls/private/ajax/Settings/configManagementWizard.html
client/htmls/private/ajax/Settings/devopsRolesWizard.html
client/htmls/private/ajax/Settings/envWizard.html
client/htmls/private/ajax/Settings/galleryWizard.html
client/htmls/private/ajax/Settings/projWizard.html
client/htmls/private/ajax/Settings/providerWizard.html
client/htmls/private/ajax/Settings/serviceCommandWizard.html
client/htmls/private/ajax/Settings/settingsWizard.html

@udeshrl : Please check and merge.

Resolved QA Bugs for settings wizard

---

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
server/app/model/classes/tasks/tasks.js

Task Model Implementation for BOTS
@kkn Plz review it and merge.

 Task Model Implementation for BOTS

---

client/cat3/Gruntfile.js
client/cat3/main.html
client/cat3/src/partials/global.scss
client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss
client/htmls/private/css/catalyst.css

Responsiveness related fixes for breadcrumb, filter options in workzone.

---

client/cat3/Gruntfile.js
client/cat3/main.html
client/cat3/src/clientRoutes.js
client/cat3/src/factory/appPermissionServices.js
client/cat3/src/main.js
client/cat3/src/partials/globals/header/headerDashboard.html
client/cat3/src/partials/sections/dashboard/dashboardCtrl.js
client/cat3/src/partials/sections/dashboard/service/service.html
client/cat3/src/partials/sections/dashboard/service/service.js
client/cat3/src/partials/sections/dashboard/service/service.scss
client/cat3/src/partials/sections/dashboard/service/view/serviceTreeMenu.html

This PR contains following items:
1.Created basic folder structure for service delivery
2.added menu item in header for service delivery
3.added htmls & controllers for service delivery
4.added left tree menu for service delivery
5.added left tree menu items clicks for navigation
6.created basic HTML structure & controller for bots library page.
7.Injected dependency for angular UI grid.

created Service Delivery folder structure,UI routing, Header menu Item, html's & controllers.

---

client/cat3/src/partials/global.scss
client/cat3/src/partials/sections/dashboard/bots/bots.html
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/library.html
client/cat3/src/partials/sections/dashboard/genericServices.js

Added API with launch function

---

client/cat3/src/partials/globals/header/headerDashboard.html
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/botsTreeMenu.html
client/htmls/private/index.html

Changed the icon

---

client/cat3/src/factory/workzoneServices.js
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/genericServices.js
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParams.html
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js

@udeshrl 
I have added env field for launch blueprint .

Blueprint Launch 

---

client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParams.html
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js

Added default select env for launch 

---

server/app/cronjobs/cron-jobs.js
server/app/model/blueprint/blueprint.js
server/app/model/classes/tasks/tasks.js
server/app/routes/v1.0/routes_blueprints.js
server/app/routes/v1.0/routes_instances.js
server/app/routes/v1.0/routes_organizations.js
server/app/routes/v1.0/routes_tasks.js

Implemented the Instance list for tagging server and soft delete for Bot .
Tag Server name is not showing in JSON for the instances which are launched from blueprint.
Ready for code review.
@kkn 
@Kaushik512

Implemented the Instance list for tagging server and soft delete for Bot 

---

client/cat3/main.html
client/cat3/src/main.js
client/cat3/src/partials/sections/dashboard/genericServices.js
client/cat3/src/partials/sections/dashboard/popups/controller/scheduleCtrl.js
client/cat3/src/partials/sections/dashboard/popups/view/schedule.html
client/cat3/src/partials/sections/dashboard/workzone/instance/instance.html
client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js

Added schedule , start, stop, function for instance

---

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/editParams.html
client/cat3/src/partials/sections/dashboard/genericServices.js

This PR contains things include:
CAT-2464 Tag Server dropdown option is showing for Parameterized jenkins job and Script Executor Jobs while executing from BOTS tab.
CAT-2466 Script parameters are not populating while Executing scripts.
CAT-2467 Validation error is showing to pass parameters when executing script Job When no parameters are passed.	
CAT-2468 When user passes paramters during script executor, its not taking latest parameters.	
CAT-2470 When user passes paramters during Jenkins job execution, its not taking latest parameters instead taking default values.

Fixed all the logged issues,Bot Library UI changes on execution.

---

client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/instance/manage/templates/cpSchedule.html

view ctrl and html changed for schedule

---

client/cat3/src/partials/global.scss
client/cat3/src/partials/sections/dashboard/design/aDesignCtrl.js
client/cat3/src/partials/sections/dashboard/design/design.html
client/cat3/src/partials/sections/dashboard/design/design.scss

Resolved height issue with ui grid tables in workzone.

---

server/app/model/classes/instance/instance.js
server/app/services/instanceService.js
server/app/services/schedulerService.js

Control Panel Issue in Scheduler

---

client/cat3/src/partials/global.scss

@udeshrl 
Infrastructure dropdown is getting overlapped with Workzone Tree structure when user clicks on Menu.

left tree CAT-2473

---

client/cat3/src/partials/sections/dashboard/bots/view/library.html
server/app/cronjobs/docker-container-sync/DockerContainerSync.js
server/app/model/audit-trail/base-audit-trail.js
server/app/model/audit-trail/bot-audit-trail.js
server/app/model/audit-trail/container-audit-trail.js
server/app/model/audit-trail/instance-audit-trail.js
server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js
server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js
server/app/model/blueprint/blueprint-types/instance-blueprint/azure-blueprint/azure-blueprint.js
server/app/model/blueprint/blueprint-types/instance-blueprint/openstack-blueprint/openstack-blueprint.js
server/app/model/blueprint/blueprint-types/instance-blueprint/vmware-blueprint/vmware-blueprint.js
server/app/model/blueprint/blueprint.js
server/app/model/classes/tasks/tasks.js
server/app/routes/v1.0/routes_blueprints.js
server/app/services/auditTrailService.js
server/app/services/taskService.js

BOTs Audit Trail Implementation

---

client/cat3/src/factory/chefDataFormatterService.js
client/cat3/src/partials/sections/dashboard/design/aDesignCtrl.js
client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js
client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js
client/cat3/src/partials/sections/dashboard/design/controllers/createCompositeCtrl.js
client/cat3/src/partials/sections/dashboard/design/design.scss
client/cat3/src/partials/sections/dashboard/design/services/blueprintListServices.js
client/cat3/src/partials/sections/dashboard/design/view/createComposite.html
client/cat3/src/partials/sections/dashboard/design/view/designListView.html
client/cat3/src/partials/sections/dashboard/genericServices.js
client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.html
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/compositeBlueprintInfo.html
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/compositeBlueprintInfoCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/cloudFormation/cloudFormation.scss
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js

Changes for Composite Blueprint and Design

---

client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/botLogsCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/botLogs.html
client/cat3/src/partials/sections/dashboard/bots/view/library.html

API integration for jenkins logs, added running bots in summary.

---

server/app/model/audit-trail/audit-trail.js
server/app/model/blueprint/blueprint.js
server/app/model/classes/tasks/tasks.js
server/app/routes/v1.0/routes_blueprints.js
server/app/routes/v1.0/routes_tasks.js
server/app/services/auditTrailService.js
server/app/services/blueprintService.js
server/app/services/taskService.js

BOTs Summary and Audit Trail Implementation

---

client/cat3/src/partials/sections/card/card.scss
client/cat3/src/partials/sections/dashboard/design/controllers/addDockerTemplateCtrl.js
client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js
client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js
client/cat3/src/partials/sections/dashboard/design/controllers/createCompositeCtrl.js
client/cat3/src/partials/sections/dashboard/design/design.html
client/cat3/src/partials/sections/dashboard/design/design.scss
client/cat3/src/partials/sections/dashboard/design/services/blueprintListServices.js
client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html
client/cat3/src/partials/sections/dashboard/design/view/createComposite.html
client/cat3/src/partials/sections/dashboard/design/view/designListView.html
client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.scss
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintInfo.html
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js

UI Modifications and QA Bugs resolved

---

client/cat3/src/partials/sections/dashboard/analytics/controller/capacityCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/botLogsCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js
client/cat3/src/partials/sections/dashboard/design/aDesignCtrl.js
client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js
client/cat3/src/partials/sections/dashboard/design/controllers/createCompositeCtrl.js
client/cat3/src/partials/sections/dashboard/genericServices.js
client/cat3/src/partials/sections/dashboard/popups/controller/orchestrationUpdateChefRunlistCtrl.js
client/cat3/src/partials/sections/dashboard/popups/controller/scheduleCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/instance/instanceCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/instance/manage/controlPanelCtrl.js

Resolved JShint errors.

---

client/cat3/src/partials/sections/dashboard/bots/bots.scss
client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/botLogsCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/audittrail.html
client/cat3/src/partials/sections/dashboard/bots/view/botLogs.html
client/cat3/src/partials/sections/dashboard/bots/view/library.html

Bots summary, Bots audittrail logs UI changes.

---

server/app/app.js
server/app/cronjobs/catalyst-scheduler/catalystScheduler.js
server/app/routes/v1.0/routes_audit_trails.js
server/app/routes/v1.0/routes_organizations.js
server/app/routes/v1.0/routes_tasks.js
server/app/services/schedulerService.js

CAT-2531/CAT-2529/CAT-2521/CAT-2532 Fixed

---

server/app/cronjobs/catalyst-scheduler/catalystScheduler.js
server/app/model/audit-trail/audit-trail.js
server/app/model/classes/tasks/tasks.js
server/app/routes/v1.0/routes_blueprints.js
server/app/routes/v1.0/routes_organizations.js
server/app/routes/v1.0/routes_tasks.js
server/app/services/blueprintService.js
server/app/services/schedulerService.js
server/app/services/taskService.js

CAT-2552 Fixed

---

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEventCtrl.js

Check for undefined and null

---

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEvent.html
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEventCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addScriptParams.html
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addScriptParamsCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
client/htmls/private/ajax/Settings/scriptList.html
client/htmls/private/js/scriptList.js
server/app/cronjobs/catalyst-scheduler/catalystScheduler.js
server/app/lib/utils/apiUtil.js
server/app/model/blueprint/blueprint.js
server/app/model/classes/tasks/taskTypeScript.js
server/app/model/classes/tasks/tasks.js
server/app/model/scripts/scripts.js
server/app/routes/v1.0/routes_blueprints.js
server/app/routes/v1.0/routes_organizations.js
server/app/routes/v1.0/routes_tasks.js
server/app/services/instanceService.js
server/app/services/schedulerService.js
server/app/services/scriptService.js
server/app/services/taskService.js

Script Executor Implementation for Python and bots library/task Scheduler Issue

---

client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addChefJobEvent.html
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html
server/app/cronjobs/catalyst-scheduler/catalystScheduler.js
server/app/model/classes/tasks/taskHistory.js
server/app/model/classes/tasks/tasks.js
server/app/routes/v1.0/routes_organizations.js
server/app/routes/v1.0/routes_tasks.js

Add Task Execution Standard Time in Task/History Schema

---

client/cat3/main.html
client/cat3/src/partials/global.scss
client/cat3/src/partials/sections/dashboard/bots/bots.scss
client/cat3/src/partials/sections/dashboard/bots/controller/botLogsCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/botInfo.html
client/cat3/src/partials/sections/dashboard/bots/view/editParams.html
client/cat3/src/partials/sections/dashboard/bots/view/library.html
client/cat3/src/partials/sections/dashboard/design/controllers/blueprintCreateCtrl.js
client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html
client/cat3/src/partials/sections/dashboard/workzone/blueprint/blueprint.scss
client/cat3/src/partials/sections/dashboard/workzone/instance/instance.scss
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTaskCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/orchestrationHistoryCtrl.js

@udeshrl , please review & merge the changes.

Bots Library, Summary enhancements, manual execution time related changes, 

---

client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryTagMappingCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/view/discoveryTagMapping.html

Array name changed

---

client/cat3/main.html
client/cat3/src/main.js
client/cat3/src/partials/sections/dashboard/track/track.html
client/cat3/src/partials/sections/dashboard/track/trackCtrl.js

Firebase test for three way bind .

firebase test

---

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/design/controllers/blueprintListCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/instance/popups/instanceLogsCtrl.js
server/app/model/blueprint/blueprint.js
server/app/model/bots/bots.js
server/app/model/classes/tasks/taskTypeChef.js
server/app/model/classes/tasks/taskTypeScript.js
server/app/routes/v1.0/routes_authentication.js
server/app/routes/v1.0/routes_d4dMasters.js
server/app/services/auditTrailService.js
server/app/services/botsService.js
server/app/services/settingsService.js
server/app/services/taskService.js

Hi @udeshrl ,
Plz verify and merge it.

Topic service delivery

---

server/app/routes/v1.0/routes_d4dMasters.js
server/app/services/settingsService.js

CAT-2558 Timeout error when user tries to create Orgadmin role.

---

client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/chefLogCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/botInfo.html

@udeshrl/ @hrushikesh07  , Please merge the changes.

Resolved QA issues related to BOTS.

---

client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/view/discoveryResources.html

single search added for ui grid

---

server/app/routes/v1.0/routes_d4dMasters.js

Hi @kkn ,
Review and merge it.

Add API validation for UserExist or not

---

client/cat3/src/partials/sections/dashboard/analytics/analytics.html
client/cat3/src/partials/sections/dashboard/analytics/analytics.js
client/cat3/src/partials/sections/dashboard/analytics/analytics.scss
client/cat3/src/partials/sections/dashboard/analytics/controller/capacityCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/controller/costCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryTagMappingCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/view/discoveryResources.html
client/cat3/src/partials/sections/dashboard/analytics/view/discoveryTagMapping.html

 select row remove

---

client/cat3/main.html
client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/controller/discoverySyncResultCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/view/discoverySyncResult.html
client/cat3/src/partials/sections/dashboard/analytics/view/instanceManage.html

Chef Import

---

client/cat3/src/partials/sections/dashboard/bots/bots.scss
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/editParams.html
client/cat3/src/partials/sections/dashboard/bots/view/library.html

New UI for Bot summary section, added scheduled bots option & API integration for the same.

---

client/cat3/src/partials/sections/dashboard/bots/view/editParams.html
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/addScriptParams.html
client/cat3/src/partials/sections/dashboard/workzone/orchestration/popups/newTask.html
server/app/model/classes/tasks/tasks.js
server/app/routes/v1.0/routes_tasks.js
server/app/services/botsService.js

BOTs QA Issue Fixed( CAT-2613,CAT-2611 and CAT-2610)

---

client/cat3/src/partials/sections/dashboard/bots/view/editParams.html
server/app/lib/utils/apiUtil.js
server/app/routes/v1.0/routes_bots.js
server/app/services/botsService.js

BOTs Search Issue

---

client/cat3/src/partials/sections/dashboard/bots/bots.scss
client/cat3/src/partials/sections/dashboard/bots/view/botInfo.html

Added internal scroll for bot info page.

---

server/app/cronjobs/catalyst-scheduler/catalystScheduler.js
server/app/services/botsService.js
server/app/services/schedulerService.js
server/app/services/taskService.js

CAT-2617 Fixed

---

client/cat3/src/partials/sections/dashboard/analytics/controller/discoveryResourcesCtrl.js

Confirm box added for edit tag value

---

server/app/db-script/monitor-update.js
server/app/model/classes/instance/instance.js

monitor migration

---

client/cat3/src/partials/sections/dashboard/analytics/analytics.js
client/cat3/src/partials/sections/dashboard/analytics/controller/capacityCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/view/capacity.html

@udeshrl 
Assigned , Managed , Unassigned .

All instance listed for capacity 

---

client/cat3/main.html
client/cat3/src/partials/sections/dashboard/analytics/analytics.js
client/cat3/src/partials/sections/dashboard/analytics/controller/capacityCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/controller/capacityReportCtrl.js
client/cat3/src/partials/sections/dashboard/analytics/view/analyticsTreeMenu.html
client/cat3/src/partials/sections/dashboard/analytics/view/capacity.html
client/cat3/src/partials/sections/dashboard/analytics/view/capacityChart.html
client/cat3/src/partials/sections/dashboard/analytics/view/capacityReport.html

RDS ,S3 listing is completed 

---

server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js
server/app/routes/v1.0/routes.js
server/app/routes/v1.0/routes_d4dMasters.js

Change routes files in settings for customer

---

client/cat3/src/partials/sections/dashboard/design/view/blueprintCreate.html
server/app/routes/v1.0/routes_authentication.js

Remove mandatory check for Instance Username for CFT Blueprint

---

client/cat3/src/partials/sections/dashboard/workzone/blueprint/popups/blueprintLaunchParamsCtrl.js
client/cat3/src/partials/sections/dashboard/workzone/instance/popups/InstanceImportByIpCtrl.js
client/htmls/private/ajax/Settings/ProvidersList.html
client/htmls/private/ajax/Settings/chefSync.html
client/htmls/private/ajax/Settings/monitoringServer.html

Added Default column for all monitors, done required changes to select default monitor everywhere.

---

client/cat3/src/partials/sections/dashboard/bots/controller/botHistoryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/library.html
server/app/model/bots/1.0/bots.js
server/app/services/auditTrailService.js
server/app/services/botsService.js

Implement Saved Time per bots and remove decimal saved time

---

client/cat3/src/partials/sections/dashboard/bots/controller/editParamsCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/library.html

Changes for Bots

---

client/cat3/src/partials/globals/loader/loaderModule.js
client/cat3/src/partials/sections/dashboard/bots/bots.scss
client/cat3/src/partials/sections/dashboard/bots/controller/audittrailCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/botLogsCtrl.js
client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/view/audittrail.html
client/cat3/src/partials/sections/dashboard/bots/view/library.html

Audit Trail Issues Resolved

---

server/app/cronjobs/task-sync/taskSync.js
server/app/model/blueprint/blueprint-types/cloud-formation-blueprint/cloud-formation-blueprint.js
server/app/model/blueprint/blueprint-types/instance-blueprint/aws-blueprint/aws-blueprint.js
server/app/model/blueprint/blueprint-types/instance-blueprint/azure-blueprint/azure-blueprint.js
server/app/model/blueprint/blueprint-types/instance-blueprint/openstack-blueprint/openstack-blueprint.js
server/app/model/blueprint/blueprint-types/instance-blueprint/vmware-blueprint/vmware-blueprint.js
server/app/model/classes/tasks/tasks.js
server/app/services/auditTrailService.js
server/app/services/botsService.js

Solved BOTs Issue

---

client/cat3/src/partials/sections/dashboard/bots/controller/libraryCtrl.js
client/cat3/src/partials/sections/dashboard/bots/tabs/param.html
client/cat3/src/partials/sections/dashboard/bots/view/botHistory.html
client/cat3/src/partials/sections/dashboard/bots/view/botInfo.html
client/cat3/src/partials/sections/dashboard/bots/view/botsDescription.html
client/cat3/src/partials/sections/dashboard/bots/view/library.html

@udeshrl : Please merge.
Resolved [CAT- 2680](https://relevancelab.atlassian.net/browse/CAT-2680)

CAT-2680: Bugs Related to BOTS
